### ISSUE TITLE
Can't get the AndroidVideoCache to work on certain devices

### ISSUE THREAD

**Issue by RUITZEI** [danikula/AndroidVideoCache#10]
Hey man, i'm currently having issues when I try to use the lib on devices such as Samsung S3 (API 18) or Nexus 4  (API 16). This is the error i'm getting on the logcat.

com.danikula.videocache.ProxyCacheException: Error using file /mnt/sdcard/Android/data/com.tar/cache/tar_gifs/http:/k30.kn3.net/taringa/1/1/5/5/8/F/vagonettas/7B9.gif.webm as disc cache
            at com.danikula.videocache.FileCache.<init>(FileCache.java:35)
            at com.tar.adapters.ShoutListCursorAdapter.handleWebmReproduction(ShoutListCursorAdapter.java:1413)
            at com.tar.adapters.ShoutListCursorAdapter$13.onClick(ShoutListCursorAdapter.java:684)
            at android.view.View.performClick(View.java:4084)
            at android.view.View$PerformClick.run(View.java:16966)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

The code I used to it is similar to the one posted on the sample. Has this library been tested on older devices like the ones I´ve just mentioned? I'm using Genymotion emulator to test this. It does work with Nexus 5, both SDK 21 and 19.

Thanks in advice, hope you can help!

**Comment by RUITZEI** [comment]
Ok, my mistake was very silly, I was using a way too long string for the name of the file and that was throwing the exception.

Thanks !

**Comment by danikula** [comment]
You used illegal name for your file `http://k30.kn3.net/taringa/1/1/5/5/8/F/vagonettas/7B9.gif.webm`.
