### ISSUE TITLE
com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280).

### ISSUE THREAD

**Issue by taany6210** [danikula/AndroidVideoCache#100]
com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:47413/ping with offset 0
                                                                 at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                                                                 at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
                                                                 at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
                                                                 at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
                                                                 at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                 at java.lang.Thread.run(Thread.java:818)
                                                              Caused by: java.io.FileNotFoundException: http://127.0.0.1:47413/ping
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
                                                                 at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
                                                                 at com.danikula.videocache.Pinger.pingServer(Pinger.java:86) 
                                                                 at com.danikula.videocache.Pinger.access$100(Pinger.java:28) 
                                                                 at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108) 
                                                                 at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104) 
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                 at java.lang.Thread.run(Thread.java:818) 
12

com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                                 at com.danikula.videocache.Pinger.ping(Pinger.java:67)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:182)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:119)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:100)
                                                                 at com.shuyu.gsyvideoplayer.GSYVideoPlayer.setUp(GSYVideoPlayer.java:240)
                                                                 at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setUp(StandardGSYVideoPlayer.java:145)
                                                                 at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setUp(StandardGSYVideoPlayer.java:140)
                                                                 at com.nanyiku.naniqlo.ui.adapter.HomeSchoolAdapter$ItemViewHolder$override.bindData(HomeSchoolAdapter.java:94)
                                                                 at com.nanyiku.naniqlo.ui.adapter.HomeSchoolAdapter$ItemViewHolder$override.access$dispatch(HomeSchoolAdapter.java)
                                                                 at com.nanyiku.naniqlo.ui.adapter.HomeSchoolAdapter$ItemViewHolder.bindData(HomeSchoolAdapter.java:0)
                                                                 at com.nanyiku.naniqlo.ui.adapter.HomeSchoolAdapter$override.onBindViewHolder(HomeSchoolAdapter.java:65)
                                                                 at com.nanyiku.naniqlo.ui.adapter.HomeSchoolAdapter$override.access$dispatch(HomeSchoolAdapter.java)
                                                                 at com.nanyiku.naniqlo.ui.adapter.HomeSchoolAdapter.onBindViewHolder(HomeSchoolAdapter.java:0)

**Comment by danikula** [comment]
Duplicates [92](https://github.com/danikula/AndroidVideoCache/issues/92)
