### ISSUE TITLE
com.danikula.videocache.ProxyCacheException

### ISSUE THREAD

**Issue by titanseason** [danikula/AndroidVideoCache#104]
Hi, I'm using this library to cache audio, 

`Uri uri = Uri.parse(proxy.getProxyUrl(url));
 mMediaPlayer.setDataSource(mContext, uri);
`

But got ProxyCacheException(s) with log below:

`D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.0.2)
D/MediaHTTPConnection: proxy null port 0
HttpProxyCacheServer error
                                                                      com.danikula.videocache.ProxyCacheException: Error processing request
                                                                          at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:240)
                                                                          at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
                                                                          at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: com.danikula.videocache.ProxyCacheException: Error reading data from http://v.rrimg.com/fmn072/audio/20161211/1720/m_QlaH_91f70005bede1e83.mp3
                                                                          at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:109)
                                                                          at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:91)
                                                                          at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:46)
                                                                          at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
                                                                          at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:233)
                                                                          at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
                                                                          at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                          at java.lang.Thread.run(Thread.java:818) 
                                                                       Caused by: java.net.ProtocolException: unexpected end of stream
                                                                          at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:445)
                                                                          at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                                          at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
                                                                          at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:105)
                                                                          at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:91) 
                                                                          at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:46) 
                                                                          at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42) 
                                                                          at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:233) 
                                                                          at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
                                                                          at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                          at java.lang.Thread.run(Thread.java:818) `

**Comment by danikula** [comment]
Can you reproduce this error on `sample` app?

**Comment by titanseason** [comment]
@danikula I'm writing a sample app, please wait

**Comment by titanseason** [comment]
I known why now.  
I should call `mMediaPlayer.prepareAsync()` rather than `mMediaPlayer.prepare()`
