### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by fmtekcan** [danikula/AndroidVideoCache#105]
Hi,
I am getting crash from HttpUrlSource.close() method, only Android 5.x devices Crashlytics says.
Crash stack trace is below:
How can I resolve this issue ? I am using version 2.6.4.
Also I am getting your Exception description:

"Wait... but why? WTF!? Really shouldn't happen any more after fixing https://github.com/danikula/AndroidVideoCache/issues/43. If you read it on your device log, please, notify me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues"

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.OkBuffer.skip(OkBuffer.java:391)
       at com.android.okio.OkBuffer.clear(OkBuffer.java:386)
       at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:205)
       at com.android.okio.RealBufferedSource$1.close(RealBufferedSource.java:187)
       at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
       at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:583)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
       at com.danikula.videocache.HttpUrlSource.close(HttpUrlSource.java:85)
       at com.danikula.videocache.ProxyCache.closeSource(ProxyCache.java:165)
       at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:140)
       at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:17)
       at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:184)
       at java.lang.Thread.run(Thread.java:818)

**Comment by danikula** [comment]
Duplicates #88
