### ISSUE TITLE
Accepting Self Signed HTTPS Certificates

### ISSUE THREAD

**Issue by nahba** [danikula/AndroidVideoCache#108]
Hi there,

I am trying this library to play HTTPS url (With self signed certificate). I am getting below exceptions.

11880-12223/com.video.example E/HttpUrlSource: Error fetching info from https://100.100.114.114/videos/video1.mp4
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
   at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212)
   at com.android.okhttp.Connection.connect(Connection.java:1322)
   at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410)
   at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131)
   at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:484)
   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:465)
   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:468)
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410)
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:532)
   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
   at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:150)
   at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:118)
   at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:60)
   at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:61)
   at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:39)
   at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
   at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:233)
   at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
   at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
   at java.lang.Thread.run(Thread.java:818)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
   at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:337)
   at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:231)
   at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
   at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:643)
   at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353)
   at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212) 
   at com.android.okhttp.Connection.connect(Connection.java:1322) 
   at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410) 
   at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131) 
   at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:484) 
   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:465) 
   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371) 
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:468) 
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410) 
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:532) 
   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) 
   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25) 
   at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:150) 
   at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:118) 
   at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:60) 
   at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:61) 
   at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:39) 
   at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42) 
   at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:233) 
   at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
   at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
   at java.lang.Thread.run(Thread.java:818) 
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
   at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:337) 
   at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:231) 
   at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115) 
   at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:643) 
   at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353) 
   at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212) 
   at com.android.okhttp.Connection.connect(Connection.java:1322) 
   at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410) 
   at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131) 
   at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:484) 
   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:465) 
   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371) 
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:468) 
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410) 
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:532) 
   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) 
   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25) 
   at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:150) 
   at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:118) 
   at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:60) 
   at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:61) 
   at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:39) 
   at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42) 
   at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:233) 
   at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
   at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
   at java.lang.Thread.run(Thread.java:818) 
   
11880-12253/com.video.example E/ProxyCache: ProxyCache error
com.danikula.videocache.ProxyCacheException: Error opening connection for https://100.100.114.114/videos/video1.mp4 with offset 0
	at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
	at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123)
	at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
	at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187)
	at java.lang.Thread.run(Thread.java:818)
 Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212)
	at com.android.okhttp.Connection.connect(Connection.java:1322)
	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410)
	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131)
	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:484)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:465)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:468)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:532)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
	at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:150)
	at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:68)
	at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123) 
	at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19) 
	at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187) 
	at java.lang.Thread.run(Thread.java:818) 
 Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:337)
	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:231)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:643)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353)
	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212) 
	at com.android.okhttp.Connection.connect(Connection.java:1322) 
	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410) 
	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131) 
	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:484) 
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:465) 
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371) 
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:468) 
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410) 
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:532) 
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) 
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25) 
	at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:150) 
	at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:68) 
	at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123) 
	at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19) 
	at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187) 
	at java.lang.Thread.run(Thread.java:818) 
 Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:337) 
	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:231) 
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115) 
	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:643) 
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353) 
	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212) 
	at com.android.okhttp.Connection.connect(Connection.java:1322) 
	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410) 
	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131) 
	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:484) 
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:465) 
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371) 
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:468) 
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410) 
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:532) 
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) 
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25) 
	at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:150) 
	at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:68) 
	at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123) 
	at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19) 
	at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187) 
	at java.lang.Thread.run(Thread.java:818)
	 
11880-12223/com.video.example E/HttpProxyCacheServer: HttpProxyCacheServer error
com.danikula.videocache.ProxyCacheException: Error processing request
  at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:240)
  at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
  at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)
Caused by: com.danikula.videocache.ProxyCacheException: Error reading source 1 times
  at com.danikula.videocache.ProxyCache.checkReadSourceErrorsCount(ProxyCache.java:59)
  at com.danikula.videocache.ProxyCache.read(ProxyCache.java:45)
  at com.danikula.videocache.HttpProxyCache.responseWithCache(HttpProxyCache.java:78)
  at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:44)
  at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
  at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:233)
  at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
  at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
  at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
  at java.lang.Thread.run(Thread.java:818)

**Comment by milleph** [comment]
Having the same issue. Can dev state whether self signed https certificates are supported?

**Comment by danikula** [comment]
IMHO self-signed certificates is almost always bad idea. `AndroidVideoCache` won't support it. Anyway you can fork project, add this feature, publish to bintray and use it at one's own risk.
