### ISSUE TITLE
ProxyCacheException

### ISSUE THREAD

**Issue by MUFCRyan** [danikula/AndroidVideoCache#113]
I meet a crash and next is the log:
Pinger: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                             com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                                 at com.danikula.videocache.Pinger.ping(Pinger.java:67)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:182)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:119)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:100)
                                                                 at com.ivydad.readtool.service.AudioPlayerService$AudioServiceBinder.cacheOrPlayAudio(AudioPlayerService.java:837)
                                                                 at com.ivydad.readtool.service.AudioPlayerService$AudioServiceBinder.play(AudioPlayerService.java:821)
                                                                 at com.ivydad.readtool.service.AudioPlayerService$AudioServiceBinder.playNewAudio(AudioPlayerService.java:723)
                                                                 at com.ivydad.readtool.service.AudioPlayerService.loadData(AudioPlayerService.java:626)
                                                                 at com.ivydad.readtool.service.AudioPlayerService.access$700(AudioPlayerService.java:75)
                                                                 at com.ivydad.readtool.service.AudioPlayerService$3.onSuccess(AudioPlayerService.java:502)
                                                                 at com.ivydad.readtool.utils.PostUtils$1.onResponse(PostUtils.java:204)
                                                                 at com.ivydad.readtool.utils.PostUtils$1.onResponse(PostUtils.java:148)
                                                                 at com.zhy.http.okhttp.OkHttpUtils$4.run(OkHttpUtils.java:259)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5600)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

the code of exception: proxyUrl = mProxy.getProxyUrl(mAudioPath);  Here the mAudioPath is a remote url of audio file

the filename generator: 
public class AudioFileNameGenerator implements FileNameGenerator {
    @Override
    public String generate(String url) {
        return Constants.PATH_FAMILY_AUDIO_ORIGINAL_CACHE + url + ".mp3";
    }
}

How can I fix the problem? I need to fix it soon

**Comment by danikula** [comment]
Duplicates #134

**Comment by alpertolgagunduzay** [comment]
**<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE"/>**
and
<application
....
android:usesCleartextTraffic="true"
>
