### ISSUE TITLE
Error pinging server 

### ISSUE THREAD

**Issue by df8969386** [danikula/AndroidVideoCache#117]
com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280).

**Comment by alokomkar** [comment]
I have run into this exception too.. Any solutions?

```
Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                                com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                                    at com.danikula.videocache.Pinger.ping(Pinger.java:67)
                                                                    at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:182)
                                                                    at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:119)
                                                                    at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:100)
                                                                    at org.rangde.literacy.handler.PlayAudioManager.playAudioFromUrl(PlayAudioManager.java:39)
                                                                    at org.rangde.literacy.fragments.QuestionFragment.playQuestionTitleAudio_aroundBody0(QuestionFragment.java:187)
                                                                    at org.rangde.literacy.fragments.QuestionFragment$AjcClosure1.run(QuestionFragment.java:1)
                                                                    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                                                                    at hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
                                                                    at org.rangde.literacy.fragments.QuestionFragment.playQuestionTitleAudio(QuestionFragment.java:177)
                                                                    at org.rangde.literacy.fragments.QuestionFragment.access$100(QuestionFragment.java:48)
                                                                    at org.rangde.literacy.fragments.QuestionFragment$1.onClick(QuestionFragment.java:126)
                                                                    at android.view.View.callOnClick(View.java:5267)
                                                                    at org.rangde.literacy.fragments.QuestionFragment$3.run(QuestionFragment.java:320)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6930)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by danikula** [comment]
Duplicates #134
