### ISSUE TITLE
com.danikula.videocache.ProxyCacheException

### ISSUE THREAD

**Issue by JerrNeon** [danikula/AndroidVideoCache#120]
Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                         com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                             at com.danikula.videocache.Pinger.ping(Pinger.java:67)
                                                             at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:182)
                                                             at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:81)
                                                             at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:52)
                                                             at com.danikula.videocache.HttpProxyCacheServer$Builder.build(HttpProxyCacheServer.java:424)
                                                             at com.shuyu.gsyvideoplayer.GSYVideoManager.newProxy(GSYVideoManager.java:172)
                                                             at com.shuyu.gsyvideoplayer.GSYVideoManager.getProxy(GSYVideoManager.java:158)
                                                             at com.shuyu.gsyvideoplayer.GSYVideoPlayer.setUp(GSYVideoPlayer.java:242)
                                                             at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setUp(StandardGSYVideoPlayer.java:195)
                                                             at com.cw.jerrbase.activity.other.VideoActivity.initGsyVideoPlayer(VideoActivity.java:45)
                                                             at com.cw.jerrbase.activity.other.VideoActivity.onCreate(VideoActivity.java:35)
                                                             at android.app.Activity.performCreate(Activity.java:5242)
                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                             at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:136)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5052)
                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by danikula** [comment]
Duplicates #134
