### ISSUE TITLE
Unable to decode stream composing_bg.png , java.io.FileNotFoundException

### ISSUE THREAD

**Issue by walterFeng** [danikula/AndroidVideoCache#125]
```
03-20 06:51:10.051 1513-1513/com.sohu.inputmethod.sogou E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/user/0/com.sohu.inputmethod.sogou/files/.theme/sogou/res/composing_bg.png (No such file or directory)
03-20 06:51:10.053 1513-1513/com.sohu.inputmethod.sogou E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/user/0/com.sohu.inputmethod.sogou/files/.theme/sogou/res/composing_bg.png (No such file or directory)
03-20 06:51:10.243 24275-24275/com.ichuanyi.icy W/Pinger: Error pinging server (attempt: 2, timeout: 280). 
03-20 06:51:10.247 24275-24275/com.ichuanyi.icy E/Pinger: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                          com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                              at com.danikula.videocache.Pinger.ping(Pinger.java:67)
                                                              at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:182)
                                                              at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:119)
                                                              at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheSer
```

**Comment by cervy** [comment]
也遇到了类似的， 希望捕获下异常

**Comment by danikula** [comment]
@cervy please use english.

**Comment by walterFeng** [comment]
cervy mean，he also encountered this error, hope you can help to solve @danikula

**Comment by danikula** [comment]
Duplicates #134
