### ISSUE TITLE
E/Pinger: Error reading ping response

### ISSUE THREAD

**Issue by Old-Geek** [danikula/AndroidVideoCache#128]
with "proxy.registerCacheListener(this, url); "

---------------------------------------------

org.oucho.radio2.cache.ProxyCacheException: Error opening connection for http://127.0.0.1:54080/ping with offset 0
                                                              at org.oucho.radio2.cache.HttpUrlSource.open(HttpUrlSource.java:71)
                                                              at org.oucho.radio2.cache.Pinger.pingServer(Pinger.java:86)
                                                              at org.oucho.radio2.cache.Pinger.access$100(Pinger.java:28)
                                                              at org.oucho.radio2.cache.Pinger$PingCallable.call(Pinger.java:108)
                                                              at org.oucho.radio2.cache.Pinger$PingCallable.call(Pinger.java:104)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                              at java.lang.Thread.run(Thread.java:818)
                                                           Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 54080): connect failed: ECONNREFUSED (Connection refused)
                                                              at libcore.io.IoBridge.connect(IoBridge.java:124)
                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                                              at java.net.Socket.connect(Socket.java:884)
                                                              at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                                                              at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
                                                              at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
                                                              at com.android.okhttp.Connection.connect(Connection.java:152)
                                                              at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                              at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                              at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
                                                              at org.oucho.radio2.cache.HttpUrlSource.openConnection(HttpUrlSource.java:146)
                                                              at org.oucho.radio2.cache.HttpUrlSource.open(HttpUrlSource.java:64)
                                                              at org.oucho.radio2.cache.Pinger.pingServer(Pinger.java:86) 
                                                              at org.oucho.radio2.cache.Pinger.access$100(Pinger.java:28) 
                                                              at org.oucho.radio2.cache.Pinger$PingCallable.call(Pinger.java:108) 
                                                              at org.oucho.radio2.cache.Pinger$PingCallable.call(Pinger.java:104) 
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                              at java.lang.Thread.run(Thread.java:818) 
                                                           Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
                                                              at libcore.io.Posix.connect(Native Method)
                                                              at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
                                                              at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
                                                              at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
                                                              at java.net.Socket.connect(Socket.java:884) 
                                                              at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117) 
                                                              at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160) 
                                                              at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67) 
                                                              at com.android.okhttp.Connection.connect(Connection.java:152) 
                                                              at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185) 
                                                              at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
                                                              at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341) 
                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330) 
                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501) 
                                                              at org.oucho.radio2.cache.HttpUrlSource.openConnection(HttpUrlSource.java:146) 
                                                              at org.oucho.radio2.cache.HttpUrlSource.open(HttpUrlSource.java:64) 
                                                              at org.oucho.radio2.cache.Pinger.pingServer(Pinger.java:86) 
                                                              at org.oucho.radio2.cache.Pinger.access$100(Pinger.java:28) 
                                                              at org.oucho.radio2.cache.Pinger$PingCallable.call(Pinger.java:108) 
                                                              at org.oucho.radio2.cache.Pinger$PingCallable.call(Pinger.java:104) 
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                              at java.lang.Thread.run(Thread.java:818) 
04-10 01:33:51.889 28528-28708/org.oucho.radio2 E/Pinger: Error reading ping response
                                                          org.oucho.radio2.cache.ProxyCacheException:

**Comment by danikula** [comment]
Duplicates #134
