### ISSUE TITLE
Can it work with mp3 cache?

### ISSUE THREAD

**Issue by huyongli** [danikula/AndroidVideoCache#131]
```
com.danikula.videocache.ProxyCacheException: Error opening connection for http://*****.mp3 with offset 34355
                                                                  at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                                                                  at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123)
                                                                  at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
                                                                  at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187)
                                                                  at java.lang.Thread.run(Thread.java:833)
                                                               Caused by: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                  at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:595)
                                                                  at libcore.io.IoBridge.recvfrom(IoBridge.java:559)
                                                                  at java.net.HwPlainSocketImpl.read(HwPlainSocketImpl.java:1110)
                                                                  at java.net.HwPlainSocketImpl$PlainSocketInputStream.readAndParseRespHeaders(HwPlainSocketImpl.java:608)
                                                                  at java.net.HwPlainSocketImpl$PlainSocketInputStream.read(HwPlainSocketImpl.java:769)
                                                                  at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
                                                                  at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                                  at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                                  at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                                  at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                                  at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                                                  at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                                  at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
                                                                  at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
                                                                  at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:150)
                                                                  at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:68)
                                                                  at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123) 
                                                                  at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19) 
                                                                  at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187) 
                                                                  at java.lang.Thread.run(Thread.java:833) 
                                                               Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                  at libcore.io.Posix.recvfromBytes(Native Method)
                                                                  at libcore.io.Posix.recvfrom(Posix.java:189)
                                                                  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                                  at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
                                                                  at java.net.HwPlainSocketImpl.read(HwPlainSocketImpl.java:1110) 
                                                                  at java.net.HwPlainSocketImpl$PlainSocketInputStream.readAndParseRespHeaders(HwPlainSocketImpl.java:608) 
                                                                  at java.net.HwPlainSocketImpl$PlainSocketInputStream.read(HwPlainSocketImpl.java:769) 
                                                                  at com.android.okhttp.okio.Okio$2.read(Okio.java:135) 
                                                                  at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211) 
                                                                  at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
                                                                  at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
                                                                  at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
                                                                  at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191) 
                                                                  at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80) 
                                                                  at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904) 
                                                                  at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788) 
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439) 
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384) 
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497) 
                                                                  at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:150) 
                                                                  at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:68) 
                                                                  at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123) 
                                                                  at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19) 
                                                                  at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187) 
                                                                  at java.lang.Thread.run(Thread.java:833) 
```

**Comment by danikula** [comment]
@huyongli Yes. It should work with **any** file. Your stacktrace just contain io problem. Check your internet connection.
