### ISSUE TITLE
not play !!!!

### ISSUE THREAD

**Issue by zhangqb** [danikula/AndroidVideoCache#133]
Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                                    com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                                        at com.danikula.videocache.Pinger.ping(Pinger.java:67)
                                                                        at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:182)
                                                                        at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:119)
                                                                        at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:100)
                                                                        at com.shuyu.gsyvideoplayer.GSYVideoPlayer.setUp(GSYVideoPlayer.java:261)
                                                                        at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setUp(StandardGSYVideoPlayer.java:195)
                                                                        at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setUp(StandardGSYVideoPlayer.java:181)
                                                                        at com.example.gsyvideoplayer.video.SampleVideo.setUp(SampleVideo.java:143)
                                                                        at com.example.gsyvideoplayer.PlayActivity.init(PlayActivity.java:72)
                                                                        at com.example.gsyvideoplayer.PlayActivity.onCreate(PlayActivity.java:49)
                                                                        at android.app.Activity.performCreate(Activity.java:6251)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                                        at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

this video uri is https://r6---sn-a5mekned.googlevideo.com/videoplayback?key=yt6&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&lmt=1492252805135564&clen=13237597&expire=1492523018&ip=118.193.19.110&gir=yes&source=youtube&mm=31&mn=sn-a5mekned&mt=1492501342&mv=m&pl=24&id=o-AIqgZcoBKUywvBgmpvNIDToU_PZWwG04LBakJBfai0iM&ei=qcP1WJa7OMzioQOLypSQBA&ms=au&requiressl=yes&mime=video%2Fmp4&dur=433.199&upn=OYZyQTLGQ3o&ipbits=0&itag=133&keepalive=yes&signature=6C73E8ECC9DE8812B7A03E9152711F8C9C5EEB18.DA993C649D5379B2E2E5CFA4897E51C661E0139B

**Comment by danikula** [comment]
Duplicates #134
