### ISSUE TITLE
How to get the Listener When thows ProxyCacheException

### ISSUE THREAD

**Issue by bingbing9527** [danikula/AndroidVideoCache#148]
My network connection has suddenly broken down，it throw Exception,but I need to do something,How to get the Listener When it thows ProxyCacheException?

05-24 10:39:35.267 14916-15787/? E/HttpProxyCacheServer: HttpProxyCacheServer error
                                                         com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.0
                                                             at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:241)
                                                             at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
                                                             at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338)
                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                             at java.lang.Thread.run(Thread.java:818)
                                                          Caused by: com.danikula.videocache.ProxyCacheException: Error opening connection for xxx.mp4 with offset 7231527. Version: 2.7.0
                                                             at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                                                             at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:89)
                                                             at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47)
                                                             at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
                                                             at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:234)
                                                             at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
                                                             at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                             at java.lang.Thread.run(Thread.java:818) 
                                                          Caused by: java.io.FileNotFoundException: xxx.mp4
                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
                                                             at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
                                                             at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:89) 
                                                             at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47) 
                                                             at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42) 
                                                             at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:234) 
                                                             at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
                                                             at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                             at java.lang.Thread.run(Thread.java:818)

**Comment by hongyang51** [comment]
I also need it!

**Comment by 1405553774** [comment]
I also need it!

**Comment by wangyongwang** [comment]
I also need it!

**Comment by gitLynn** [comment]
I also need it!

**Comment by RowlandOti** [comment]
I need this too. Not too much to ask.
