### ISSUE TITLE
android 4.4.2 log HttpProxyCacheServer can't run.

### ISSUE THREAD

**Issue by hongyang51** [danikula/AndroidVideoCache#149]
`E/HttpProxyCacheServer(12152): HttpProxyCacheServer error
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.0
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:241)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at java.lang.Thread.run(Thread.java:841)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): Caused by: com.danikula.videocache.ProxyCacheException: Error using file /storage/emulated/0/Android/data/com.zhuomogroup.ylyk/cache/video-cache/d807f4345139053b1517df0a639f3efc as disc cache. Version: 2.7.0
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.file.FileCache.<init>(FileCache.java:39)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServerClients.newHttpProxyCache(HttpProxyCacheServerClients.java:83)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServerClients.startProcessRequest(HttpProxyCacheServerClients.java:49)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:39)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:234)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	... 7 more
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): Caused by: java.io.IOException: Directory /storage/emulated/0/Android/data/com.zhuomogroup.ylyk/cache/video-cache can't be created
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.file.Files.makeDir(Files.java:33)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.file.FileCache.<init>(FileCache.java:34)
05-27 14:54:54.835 E/HttpProxyCacheServer(12152): 	... 11 more
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): HttpProxyCacheServer error
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.0
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:241)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at java.lang.Thread.run(Thread.java:841)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): Caused by: com.danikula.videocache.ProxyCacheException: Error using file /storage/emulated/0/Android/data/com.zhuomogroup.ylyk/cache/video-cache/d807f4345139053b1517df0a639f3efc as disc cache. Version: 2.7.0
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.file.FileCache.<init>(FileCache.java:39)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServerClients.newHttpProxyCache(HttpProxyCacheServerClients.java:83)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServerClients.startProcessRequest(HttpProxyCacheServerClients.java:49)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:39)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:234)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	... 7 more
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): Caused by: java.io.IOException: Directory /storage/emulated/0/Android/data/com.zhuomogroup.ylyk/cache/video-cache can't be created
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.file.Files.makeDir(Files.java:33)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	at com.danikula.videocache.file.FileCache.<init>(FileCache.java:34)
05-27 14:54:54.845 E/HttpProxyCacheServer(12152): 	... 11 more
`

Read and write access has given

**Comment by JoaoArmandoo** [comment]
I'm also having this problem, have you solved it?
in android 5.0

**Comment by JoaoArmandoo** [comment]
I just cleaned the application's cache data manually, and the error stopped.
