### ISSUE TITLE
ava.lang.NoClassDefFoundError: org.slf4j.LoggerFactory

### ISSUE THREAD

**Issue by xjd1987** [danikula/AndroidVideoCache#151]
java.lang.NoClassDefFoundError: org.slf4j.LoggerFactory
                                                                       at com.danikula.videocache.HttpProxyCacheServer.<clinit>(HttpProxyCacheServer.java:54)
                                                                       at cn.youbeitong.smart.MApplication.newProxy(MApplication.java:113)
                                                                       at cn.youbeitong.smart.MApplication.getProxy(MApplication.java:109)
                                                                       at cn.youbeitong.smart.activity.VideoPlayActivity.setVideoPlay(VideoPlayActivity.java:335)
                                                                       at cn.youbeitong.smart.activity.VideoPlayActivity.init(VideoPlayActivity.java:227)
                                                                       at cn.youbeitong.smart.activity.VideoPlayActivity.initDatas(VideoPlayActivity.java:203)
                                                                       at cn.youbeitong.smart.base.BaseActivity.onCreate(BaseActivity.java:61)
                                                                       at android.app.Activity.performCreate(Activity.java:5135)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
                                                                       at android.app.ActivityThread.access$600(ActivityThread.java:165)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                       at android.os.Looper.loop(Looper.java:194)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5400)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:525)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by xjd1987** [comment]
android 4.2.2

**Comment by danikula** [comment]
@xjd1987 do you use proguard or shrinker ?

**Comment by xjd1987** [comment]
@danikula  no ,and it only occur in android 4.2.2  lenovo phone
