### ISSUE TITLE
NoClassDefFoundError: org.slf4j.helpers.SubstituteLoggerFactory

### ISSUE THREAD

**Issue by saefbadwan** [danikula/AndroidVideoCache#167]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.network.imyth.network, PID: 21266
                                                                           java.lang.NoClassDefFoundError: org.slf4j.helpers.SubstituteLoggerFactory
                                                                               at org.slf4j.LoggerFactory.<clinit>(LoggerFactory.java:86)
                                                                               at com.danikula.videocache.StorageUtils.<clinit>(StorageUtils.java:23)
                                                                               at com.danikula.videocache.HttpProxyCacheServer$Builder.<init>(HttpProxyCacheServer.java:356)
                                                                               at com.network.imyth.network.global_functions.newProxy(global_functions.java:377)
                                                                               at com.network.imyth.network.global_functions.getProxy(global_functions.java:372)
                                                                               at com.network.imyth.network.MainWindow_page_1$RecyclerAdapter$NewPostHolder.<init>(MainWindow_page_1.java:855)
                                                                               at com.network.imyth.network.MainWindow_page_1$RecyclerAdapter.onCreateViewHolder(MainWindow_page_1.java:1309)
                                                                               at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                               at android.view.View.layout(View.java:14840)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4664)
                                                                               at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                               at android.view.View.layout(View.java:14840)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4664)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
                                                                               at android.view.View.layout(View.java:14840)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4664)
                                                                               at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                               at android.view.View.layout(View.java:14840)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4664)
                                                                               at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                               at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                               at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1391)
                                                                               at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                               at android.view.View.layout(View.java:14840)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4664)
                                                                               at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                               at android.view.View.layout(View.java:14840)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4664)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                               at android.view.View.layout(View.java:14840)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4664)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
                                                                               at android.view.View.layout(View.java:14840)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4664)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                               at android.view.View.layout(View.java:14840)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4664)
                                                                           	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697

**Comment by saefbadwan** [comment]
I download version 2.6.4 all working normal after half a day digging in this ,,, it seems that you changed some code and it's updated in my project and causes this problem
