### ISSUE TITLE
我在我的日志里莫名就看到这个了,还有这种操作

### ISSUE THREAD

**Issue by qq517103430** [danikula/AndroidVideoCache#168]
com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                             at com.danikula.videocache.Pinger.ping(Pinger.java:67)
                                                             at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:182)
                                                             at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:81)
                                                             at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:52)
                                                             at com.danikula.videocache.HttpProxyCacheServer$Builder.build(HttpProxyCacheServer.java:424)
                                                             at com.gotokeep.keep.KApplication.lambda$initInMainThread$851(KApplication.java:182)
                                                             at com.gotokeep.keep.e.a(Unknown Source)

**Comment by shuide** [comment]
我也看到了这个,这是什么呀

**Comment by ChanJLee** [comment]
speak english
