### ISSUE TITLE
OutOfMemoryErrordeocache:2.7.0'

### ISSUE THREAD

**Issue by crazies** [danikula/AndroidVideoCache#193]
compile 'com.danikula:videocache:2.7.0'
     Stack trace:  
                                                            java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
                                                                at java.lang.Thread.nativeCreate(Native Method)
                                                                at java.lang.Thread.start(Thread.java:745)
                                                                at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
                                                                at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1348)
                                                                at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:89)
                                                                at com.danikula.videocache.HttpProxyCacheServer.waitForRequest(HttpProxyCacheServer.java:218)
                                                                at com.danikula.videocache.HttpProxyCacheServer.access$100(HttpProxyCacheServer.java:52)
                                                                at com.danikula.videocache.HttpProxyCacheServer$WaitRequestsRunnable.run(HttpProxyCacheServer.java:324)
                                                                at java.lang.Thread.run(Thread.java:776)
12-25 15:43:55.572 445-7493/? E/ion: set flags ioctrl failed!

**Comment by crazies** [comment]
出现了概率性的内存不足，能解决吗？不能解决的话，我只能撤销缓存功能了，好无奈

**Comment by 897902334** [comment]
@crazies   哥们    什么情况下会出现内存溢出？？？   我现在也是用的这个库，吓得我快不敢用了！！   一般什么手机会出现这个问题呢？低内存手机么？

**Comment by xuzhiyong017** [comment]
我现在也遇到了内存溢出的问题，主要是在不停的发送缓存请求的情况下出现的，目前还没有解决

**Comment by LvBing1995** [comment]
我现在也是,有人说下怎么解决吗
