### ISSUE TITLE
偶尔会有如下崩溃信息出现

### ISSUE THREAD

**Issue by chenxi0203** [danikula/AndroidVideoCache#199]
HttpProxyCacheServer error
                                                                           com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.0
                                                                               at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:241)
                                                                               at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
                                                                               at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338)
                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by zhoulubo** [comment]
me too (Android 7.0)

**Comment by DevXue** [comment]
@zhoulubo  @chenxi0203   请问2位在使用的时候，  是APP直接闪退了？  还是只会Log控制台出现这种异常？

**Comment by zhoulubo** [comment]
没有闪退，会出现log发自我的华为手机-------- 原始邮件 --------主题：Re: [danikula/AndroidVideoCache] 偶尔会有如下崩溃信息出现 (#199)发件人：薛 收件人：danikula/AndroidVideoCache 抄送：zhoulubo <2485003@163.com>,Mention @zhoulubo  @chenxi0203   请问2位在使用的时候，  是APP直接闪退了？  还是只会Log控制台出现这种异常？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/danikula/AndroidVideoCache","title":"danikula/AndroidVideoCache","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/danikula/AndroidVideoCache"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DevXue in #199: @zhoulubo  @chenxi0203   请问2位在使用的时候，  是APP直接闪退了？  还是只会Log控制台出现这种异常？"}],"action":{"name":"View Issue","url":"https://github.com/danikula/AndroidVideoCache/issues/199#issuecomment-364637109"}}}

**Comment by zhangpingV5** [comment]
@chenxi0203 @zhoulubo @DevXue 请问各位都解决了吗？同样遇到这样的问题。
