### ISSUE TITLE
 Error closing socket input stream. Version: 2.7.1

### ISSUE THREAD

**Issue by selimonline** [danikula/AndroidVideoCache#223]
Device : Samsung s7
Version : 2.7.1
Sdk Version : 27

HttpProxyCacheServer proxy = new HttpProxyCacheServer(this);
String proxyUrl = proxy.getProxyUrl("HTTPS URL");

here is details logs : 

26503-27478/com.oevo E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error closing socket input stream. Version: 2.7.1
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:287)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:272)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:245)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:267)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582)
        at java.net.Socket.shutdownInput(Socket.java:1565)
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:280)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:272) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:245) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:176)

**Comment by Se7eNHea7eN** [comment]
same problem

**Comment by liaohuyu** [comment]
~~same

**Comment by fflin** [comment]
same

**Comment by cxmmxc** [comment]
same!~~

**Comment by Rambobingo** [comment]
same +1

**Comment by LiXuSpace** [comment]
same+1 , please help !

**Comment by cxmmxc** [comment]
I give up!

**Comment by anantshah93** [comment]
Same+1

**Comment by anubhavmalik** [comment]
+1

**Comment by Panxiaoan1993** [comment]
same！please help.

**Comment by HiveUnion** [comment]
same～help

**Comment by juanlabrador** [comment]
same

**Comment by YuJunKui1995** [comment]
same+1

**Comment by WongChoBun** [comment]
相同+1

**Comment by langrenfengzi** [comment]
any fix?

**Comment by luquick** [comment]
any fix?

**Comment by luodongwen** [comment]
oh, same~

**Comment by hxkdidi** [comment]
i encounter the same problems and crash。

**Comment by dbarmagan** [comment]
@danikula we are waiting your answers here.

**Comment by songhongwang** [comment]
same + 1

**Comment by clipperL** [comment]
same+1

**Comment by xingjian8854** [comment]
same +1

**Comment by atomofiron** [comment]
same +1

**Comment by gitJusth** [comment]
same +1

**Comment by pcg92** [comment]
whats happening?

**Comment by gybguohao** [comment]
same+1, any fix?

**Comment by pratikbutani** [comment]
Any solution? @danikula

**Comment by vittoridavide** [comment]
same

**Comment by ray-yuruisoft** [comment]
same+1

**Comment by otakutronic** [comment]
same+2

**Comment by humanheima** [comment]
same + 1

**Comment by qinxianyuzou** [comment]
same + 1

**Comment by sun55** [comment]
samsung s8, same +1

**Comment by tao111222333444** [comment]
same +1

**Comment by sidleciel** [comment]
mix3 same+1

**Comment by avdkishore** [comment]
will there be a fix for this issue ?

**Comment by pratikbutani** [comment]
Did anyone get the solution?

**Comment by onexuan** [comment]
same+1 @danikula

**Comment by vedprakashsah1998** [comment]
same

**Comment by subhan9090** [comment]
Same bro Kindly update!!!

**Comment by SanChunAndrroid** [comment]
+1

**Comment by MrRoboots** [comment]
+1

**Comment by parthbhatti** [comment]
+1

**Comment by HunterPillu** [comment]
same +1

**Comment by rohanprasadofficial** [comment]
same here , any fix ?

**Comment by TeilzeitTaco** [comment]
^

**Comment by VivekMakwana24** [comment]
Any fix? @danikula  
Its urgent

**Comment by VomPom** [comment]
same question.

**Comment by VomPom** [comment]
@selimonline have you solved this problem?

**Comment by cervy** [comment]
same， and with ANR...

**Comment by vsnain** [comment]
Is the library owner still alive?

**Comment by Umesh-Kumar19** [comment]
same issue +1

**Comment by pravynandas** [comment]
Same issue +1

**Comment by wcdxg** [comment]
+1

**Comment by gongkaiqiang** [comment]
+1

**Comment by pratikbutani** [comment]
If you can't solve it. Please add all the issue in lable **hacktoberfest** so someone may help.

Hope everyone agreed.

**Comment by verketh** [comment]
+1

**Comment by neopraveen** [comment]
Same here +1

**Comment by czw299** [comment]
same

**Comment by quydangdac** [comment]
Same +1

**Comment by kksingla** [comment]
same +1

**Comment by micromingle** [comment]
same +1 @danikula  Are you ok , we worry about you .

**Comment by bhumikash-tech** [comment]
same, I also got the same error. @danikula please update its kinda urgent. Or if anyone got the solution please reply to this problem.

**Comment by goodnightmycat** [comment]
![image](https://user-images.githubusercontent.com/49119923/146500631-e61e51a0-6dbf-46ca-b4ef-3bdacb57e73a.png)
change the if statement to  if (!socket.isInputShutdown()&&socket.isConnected()) might fix the error

**Comment by VomPom** [comment]
尊敬的先生/女士：
					
				
				
					
						
							   您好！您发送的邮件我已经收到，我回尽快回复您。   谢谢!

						
					
				
				
				
					
						
							

								
									--王鹏（落叶挽歌）

**Comment by fatemi2020** [comment]
same +1
Samsung A71

**Comment by pravynandas** [comment]
I think the bug waited long enough. I'm gonna attempt to find a fix or at least get the bottom of the issue. Inputs, suggestions, comments or concerns are all welcome.

**Comment by VomPom** [comment]
尊敬的先生/女士：
					
				
				
					
						
							   您好！您发送的邮件我已经收到，我回尽快回复您。   谢谢!

						
					
				
				
				
					
						
							

								
									--王鹏（落叶挽歌）

**Comment by zhouhuandev** [comment]
same +1

**Comment by haybl** [comment]
same exception when using MediaPlayer, but not in ExoPlayer.

**Comment by Jamoliddin2001** [comment]
Change cache directory

`val proxyServer = HttpProxyCacheServer`
             `.Builder(context)`
             `.cacheDirectory(context.filesDir)`
             `.maxCacheSize(1024 * 1024 * 1024)`
             `.build()`
`val proxyURL = proxyServer.getProxyUrl(sourceUrl)`

**Comment by 0x41rtur** [comment]
+1

**Comment by Berkay92** [comment]
Hi everyone who is suffering from this disgusting error!
I have figured out something in my source code that causes this error.

I was trying to open a connection from a URL and then read the InputStream for my use case.
```InputStream is = null;
try {
    URLConnection conn = new URL(proxyUrl).openConnection();
    conn.setConnectTimeout(5000);
    conn.setReadTimeout(5000);
    conn.connect();
    is = conn.getInputStream();

} catch (MalformedURLException e) {
    throw new RuntimeException(e);
} catch (IOException e) {
    throw new RuntimeException(e);
}
```

When I try to remove these lines, the error has gone.
I hope this information will also help you identify the root cause.

Happy coding..
