### ISSUE TITLE
The Problem whith m3u8 cache

### ISSUE THREAD

**Issue by zqq5054** [danikula/AndroidVideoCache#227]
I found that AndroidVideoCache can cache the m3u8,because i found the cahe file in the disk,but,the player can not play the video,I do not know why? it is a AndroidVideoCache bug or the player's bug?

**Comment by zqq5054** [comment]
And  I get this error
 com.danikula.videocache.ProxyCacheException: Error closing socket input stream. Version: 1.2
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:287)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:272)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:245)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:345)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:267)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582)
        at java.net.Socket.shutdownInput(Socket.java:1565)
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:280)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:272) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:245) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:345) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:178)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:265)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582) 
        at java.net.Socket.shutdownInput(Socket.java:1565) 
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:280) 
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:272) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:245) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:345) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by JeffMony** [comment]
Maybe you can try it, https://github.com/JeffMony/JeffVideoCache
