### ISSUE TITLE
HttpProxyCacheServer error ,can`t play the video

### ISSUE THREAD

**Issue by zhangpingV5** [danikula/AndroidVideoCache#231]
version ：android 5.1

Problem Description ：Playing a video for the first time will occasionally fail to play. Many people have mentioned this question, I hope you can help solve  .

Possible cause: load timeout. Such as the following: 1. The network status is not good; 2. The video length is longer; 3. The CDN resource is not good.

```
2-15 17:29:50.600 12822-12822/android.upedu.business E/RecyclerView: No adapter attached; skipping layout
12-15 17:29:50.680 12822-12822/android.upedu.business E/RecyclerView: No adapter attached; skipping layout
12-15 17:29:50.857 12822-12822/android.upedu.business E/RecyclerView: No adapter attached; skipping layout
12-15 17:29:50.874 164-521/? E/FFPlayerHelper: isBDDirectory() ,path = http://127.0.0.1:57682/https%3A%2F%2Ftouch.hopechina.cc%2Fcjh_10840_video_1539937387982.mp4
12-15 17:29:50.874 164-521/? E/FFPlayerHelper: isBDDirectory(): no BDMV
12-15 17:29:50.874 164-521/? E/RockFFPlayerBase: MediaServer is SP_FOREGROUND, tid=521
12-15 17:29:50.874 164-521/? E/FFPlayerHelper: efuse open fail
12-15 17:29:50.875 164-521/? E/RkExtensionPlayer: createDirectory(), path = /tmp/subtitle/
12-15 17:29:50.875 164-521/? E/RkExtensionPlayer: createDirectory(), directory = /tmp/subtitle/ already exist
12-15 17:29:50.875 164-521/? E/TraceThread: TraceThread::randomUID() --> [UID=6f0abb3b]
12-15 17:29:50.875 164-13961/? E/TraceThread:     VsyncReciver(tid = 2718839696)--> [UID=6f0abb3b] VsyncReciver::startthread
12-15 17:29:50.875 164-521/? E/TraceThread:     RockFFPlayer(tid = 3089002896)--> [UID=6f0abb3b] FFMPlayer Construction; object=0xab679a20
12-15 17:29:50.884 164-13963/? E/RockFFPlayerBase: openContext : in
12-15 17:29:50.884 164-13963/? E/RockFFPlayer: ffmpeg version 10-26
12-15 17:29:50.884 164-13963/? E/RockFFPlayer: May Be MP4 file type
12-15 17:29:50.884 164-13963/? E/RockFFPlayer: ffio_fdopen:MP4,IO_BUFFER_SIZE set 1MB
12-15 17:29:52.012 164-13963/? E/RockFFPlayer: av_probe_input_buffer:avio_read
12-15 17:29:52.012 164-13963/? E/RockFFPlayer: Hery, probe size = 3
12-15 17:29:52.012 164-13963/? E/RockFFPlayer: avformat_open_input:read_header
12-15 17:29:55.121 164-13963/? E/RockFFPlayer: tcp:TIMEOUT:3000000
12-15 17:29:55.124 164-13963/? E/RockFFPlayer: moov atom not found
12-15 17:29:55.124 164-13963/? E/RockFFPlayerBase: network ExtendSubtitle isn't supported....
12-15 17:29:55.124 164-13963/? E/FFExtensionSource: ~FFExtensionSource in
12-15 17:29:55.124 164-13963/? E/FFExtensionSource: ~FFExtensionSource out
12-15 17:29:55.124 164-13963/? E/RockFFPlayerBase: openContext : out,ret = -1094995529
12-15 17:29:55.124 164-13963/? E/RockFFPlayerBase: openContext : in
12-15 17:29:55.124 164-13963/? E/RockFFPlayer: ffmpeg version 10-26
12-15 17:29:55.125 164-13963/? E/RockFFPlayer: May Be MP4 file type
12-15 17:29:55.125 164-13963/? E/RockFFPlayer: ffio_fdopen:MP4,IO_BUFFER_SIZE set 1MB
12-15 17:29:55.132 164-13963/? E/RockFFPlayer: av_probe_input_buffer:avio_read
12-15 17:29:55.132 164-13963/? E/RockFFPlayer: Hery, probe size = 3
12-15 17:29:55.133 164-13963/? E/RockFFPlayer: avformat_open_input:read_header
12-15 17:29:58.238 164-13963/? E/RockFFPlayer: tcp:TIMEOUT:3000000
12-15 17:29:58.241 164-13963/? E/RockFFPlayer: moov atom not found
12-15 17:29:58.241 164-13963/? E/RockFFPlayerBase: network ExtendSubtitle isn't supported....
12-15 17:29:58.241 164-13963/? E/RockFFPlayerBase: openContext : out,ret = -1094995529
12-15 17:29:58.241 164-13963/? E/RockFFPlayerBase: openContext : in
12-15 17:29:58.241 164-13963/? E/RockFFPlayer: ffmpeg version 10-26
12-15 17:29:58.241 164-13963/? E/RockFFPlayer: May Be MP4 file type
12-15 17:29:58.241 164-13963/? E/RockFFPlayer: ffio_fdopen:MP4,IO_BUFFER_SIZE set 1MB
12-15 17:29:58.245 164-13963/? E/RockFFPlayer: av_probe_input_buffer:avio_read
12-15 17:29:58.245 164-13963/? E/RockFFPlayer: Hery, probe size = 3
12-15 17:29:58.246 164-13963/? E/RockFFPlayer: avformat_open_input:read_header
12-15 17:30:00.131 477-552/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=3089.15 rxSuccessRate=14290.45 targetRoamBSSID=48:7d:2e:f2:27:30 RSSI=-46
12-15 17:30:00.131 477-552/system_process E/WifiStateMachine: startDelayedScan send -> 616 milli 20000
12-15 17:30:00.131 477-552/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN with age=5992790 interval=101250 maxinterval=300000
12-15 17:30:00.131 477-552/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN try full band scan age=5992790 interval=101250 maxinterval=300000
12-15 17:30:00.131 477-552/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN prevent full band scan due to pkt rate
12-15 17:30:00.131 477-552/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 ...and ignore scans tx=3089.15 rx=14290.45
12-15 17:30:01.351 164-13963/? E/RockFFPlayer: tcp:TIMEOUT:3000000
12-15 17:30:01.355 164-13963/? E/RockFFPlayer: moov atom not found
12-15 17:30:01.355 164-13963/? E/RockFFPlayerBase: network ExtendSubtitle isn't supported....
12-15 17:30:01.355 164-13963/? E/RockFFPlayerBase: openContext : out,ret = -1094995529
12-15 17:30:01.355 164-13963/? E/RockFFPlayerBase: openContext : in
12-15 17:30:01.355 164-13963/? E/RockFFPlayer: ffmpeg version 10-26
12-15 17:30:01.355 164-13963/? E/RockFFPlayer: May Be MP4 file type
12-15 17:30:01.355 164-13963/? E/RockFFPlayer: ffio_fdopen:MP4,IO_BUFFER_SIZE set 1MB
12-15 17:30:01.357 164-13963/? E/RockFFPlayer: av_probe_input_buffer:avio_read
12-15 17:30:01.357 164-13963/? E/RockFFPlayer: Hery, probe size = 3
12-15 17:30:01.358 164-13963/? E/RockFFPlayer: avformat_open_input:read_header
12-15 17:30:04.465 164-13963/? E/RockFFPlayer: tcp:TIMEOUT:3000000
12-15 17:30:04.470 164-13963/? E/RockFFPlayer: moov atom not found
12-15 17:30:04.470 164-13963/? E/RockFFPlayerBase: network ExtendSubtitle isn't supported....
12-15 17:30:04.470 164-13963/? E/RockFFPlayerBase: openContext : out,ret = -1094995529
12-15 17:30:04.470 164-13963/? E/RockFFPlayerBase: openContext : in
12-15 17:30:04.470 164-13963/? E/RockFFPlayer: ffmpeg version 10-26
12-15 17:30:04.470 164-13963/? E/RockFFPlayer: May Be MP4 file type
12-15 17:30:04.470 164-13963/? E/RockFFPlayer: ffio_fdopen:MP4,IO_BUFFER_SIZE set 1MB
12-15 17:30:04.474 164-13963/? E/RockFFPlayer: av_probe_input_buffer:avio_read
12-15 17:30:04.474 164-13963/? E/RockFFPlayer: Hery, probe size = 3
12-15 17:30:04.474 164-13963/? E/RockFFPlayer: avformat_open_input:read_header
12-15 17:30:07.578 164-13963/? E/RockFFPlayer: tcp:TIMEOUT:3000000
12-15 17:30:07.581 164-13963/? E/RockFFPlayer: moov atom not found
12-15 17:30:07.581 164-13963/? E/RockFFPlayerBase: network ExtendSubtitle isn't supported....
12-15 17:30:07.581 164-13963/? E/RockFFPlayerBase: openContext : out,ret = -1094995529
12-15 17:30:07.582 12822-12891/android.upedu.business E/MediaPlayer: error (-1003, -1094995529)
12-15 17:30:07.583 12822-12891/android.upedu.business E/MediaPlayer: error (1, -2147483648)
12-15 17:30:07.610 12822-12822/android.upedu.business E/MediaPlayer: Error (-1003,-1094995529)
12-15 17:30:07.611 12822-12822/android.upedu.business E/MediaPlayer: Error (1,-2147483648)
12-15 17:30:20.134 477-552/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=4004.28 rxSuccessRate=16802.12 targetRoamBSSID=48:7d:2e:f2:27:30 RSSI=-46
12-15 17:30:20.134 477-552/system_process E/WifiStateMachine: startDelayedScan send -> 617 milli 20000
12-15 17:30:20.134 477-552/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN with age=6012793 interval=101250 maxinterval=300000
12-15 17:30:20.134 477-552/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN try full band scan age=6012793 interval=101250 maxinterval=300000
12-15 17:30:20.134 477-552/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN prevent full band scan due to pkt rate
12-15 17:30:20.135 477-552/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 ...and ignore scans tx=4004.28 rx=16802.12
12-15 17:30:21.451 164-13969/? E/NuCachedSource2: source returned error -1010, 0 retries left
12-15 17:30:21.451 164-9128/? E/MetadataRetrieverClient: failed to capture a video frame
12-15 17:30:21.451 12822-13967/android.upedu.business E/MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
12-15 17:30:21.856 164-13966/? E/NuCachedSource2: source returned error -1010, 0 retries left
12-15 17:30:22.176 12822-12897/android.upedu.business E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.1
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.danikula.videocache.ProxyCacheException: Error reading data from https://touch.hopechina.cc/cjh_10840_video_1539937387982.mp4. Version: 2.7.1
        at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:129)
        at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:92)
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47)
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.net.ProtocolException: unexpected end of stream
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
        at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
        at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:125)
        at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:92) 
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47) 
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
12-15 17:30:22.674 12822-12822/android.upedu.business E/MediaPlayer: stop called in state 0
12-15 17:30:22.674 12822-12822/android.upedu.business E/MediaPlayer: error (-38, 0)
12-15 17:30:22.676 164-13962/? E/RockFFPlayerBase: FFMPlayerBase::flushRenderQueue in
12-15 17:30:22.676 164-13962/? E/RockFFPlayerBase: FFMPlayerBase::flushRenderQueue out
12-15 17:30:22.678 164-14005/? E/RockFFPlayerBase: closeContext : in
12-15 17:30:22.678 164-14005/? E/RockFFPlayerBase: closeContext : out
12-15 17:30:22.679 164-164/? E/FFPlayer: ~FFPlayer
12-15 17:30:22.685 164-164/? E/TraceThread:     VsyncReciver(tid = 2718839696)--> [UID=6f0abb3b] pthread_join begin-->player = 0xab679a20
12-15 17:30:22.693 164-164/? E/TraceThread:     VsyncReciver(tid = 2718839696)--> [UID=6f0abb3b] pthread_join   end-->player = 0xab679a20
12-15 17:30:22.693 164-164/? E/TraceThread:     RockFFPlayer(tid = 3070065644)--> [UID=6f0abb3b] ~FFMPlayer Destruction; object=0xab679a20
12-15 17:30:25.260 12822-13033/android.upedu.business E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.1
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.danikula.videocache.ProxyCacheException: Error reading data from https://touch.hopechina.cc/cjh_10840_video_1539937387982.mp4. Version: 2.7.1
        at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:129)
        at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:92)
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47)
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.net.ProtocolException: unexpected end of stream
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
        at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
        at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:125)
        at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:92) 
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47) 
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
12-15 17:30:28.415 12822-13015/android.upedu.business E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.1
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.danikula.videocache.ProxyCacheException: Error reading data from https://touch.hopechina.cc/cjh_10840_video_1539937387982.mp4. Version: 2.7.1
        at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:129)
        at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:92)
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47)
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.net.ProtocolException: unexpected end of stream
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
        at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
        at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:125)
        at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:92) 
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47) 
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
12-15 17:30:31.515 12822-13032/android.upedu.business E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.1
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.danikula.videocache.ProxyCacheException: Error reading data from https://touch.hopechina.cc/cjh_10840_video_1539937387982.mp4. Version: 2.7.1
        at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:129)
        at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:92)
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47)
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.net.ProtocolException: unexpected end of stream
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
        at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
        at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:125)
        at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:92) 
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47) 
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
12-15 17:30:34.618 12822-13021/android.upedu.business E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.1
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.danikula.videocache.ProxyCacheException: Error reading data from https://touch.hopechina.cc/cjh_10840_video_1539937387982.mp4. Version: 2.7.1
        at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:129)
        at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:92)
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47)
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.net.ProtocolException: unexpected end of stream
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
        at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
        at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:125)
        at com.danikula.videocache.HttpProxyCache.responseWithoutCache(HttpProxyCache.java:92) 
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:47) 
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by zhangpingV5** [comment]
@danikula Please help fix this bug. I am usering the ijkplayer

**Comment by Chaosxing** [comment]
When the request encounters an error network resource, a cache file of size zero will still be cached, eventually causing the player to not play the cache file properly.

**Comment by rohanprasadofficial** [comment]
> When the request encounters an error network resource, a cache file of size zero will still be cached, eventually causing the player to not play the cache file properly.

@Chaosxing  do you have any solution for this ?

**Comment by RyanHuen** [comment]
r u using local cache to proxy?
