### ISSUE TITLE
 com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.1

### ISSUE THREAD

**Issue by Jay-YaoJie** [danikula/AndroidVideoCache#260]
https://lbtafx.oss-cn-shenzhen.aliyuncs.com/video/mp4/db14d201908231421197737.mp4

2019-08-25 12:40:02.027 10273-10665/com.hldm.lbtafxapp I/Pinger: Ping response: `ping ok`, pinged? true
2019-08-25 12:40:02.038 10273-10273/com.hldm.lbtafxapp D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
2019-08-25 12:40:02.038 10273-10273/com.hldm.lbtafxapp D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
2019-08-25 12:40:02.038 10273-10273/com.hldm.lbtafxapp V/IJKMEDIA: setDataSource: path http://127.0.0.1:40538/https%3A%2F%2Flbtafx.oss-cn-shenzhen.aliyuncs.com%2Fvideo%2Fmp4%2Fdb14d201908231421197737.mp4
2019-08-25 12:40:02.038 10273-10273/com.hldm.lbtafxapp D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:40538/https%3A%2F%2Flbtafx.oss-cn-shenzhen.aliyuncs.com%2Fvideo%2Fmp4%2Fdb14d201908231421197737.mp4")
2019-08-25 12:40:02.038 10273-10273/com.hldm.lbtafxapp D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:40538/https%3A%2F%2Flbtafx.oss-cn-shenzhen.aliyuncs.com%2Fvideo%2Fmp4%2Fdb14d201908231421197737.mp4")=0
2019-08-25 12:40:02.038 10273-10273/com.hldm.lbtafxapp D/IJKMEDIA: IjkMediaPlayer_prepareAsync
2019-08-25 12:40:02.038 10273-10273/com.hldm.lbtafxapp D/IJKMEDIA: ijkmp_prepare_async()
2019-08-25 12:40:02.039 10273-10669/com.hldm.lbtafxapp I/IJKMEDIA: SDL_RunThread: [10669] ff_msg_loop
2019-08-25 12:40:02.039 10273-10669/com.hldm.lbtafxapp D/IJKMEDIA: message_loop
2019-08-25 12:40:02.039 10273-10273/com.hldm.lbtafxapp D/IJKMEDIA: ijkmp_prepare_async()=0
2019-08-25 12:40:02.039 10273-10670/com.hldm.lbtafxapp I/IJKMEDIA: SDL_RunThread: [10670] ff_vout
2019-08-25 12:40:02.039 10273-10671/com.hldm.lbtafxapp I/IJKMEDIA: SDL_RunThread: [10671] ff_read

2019-08-25 12:40:02.063 10273-10672/com.hldm.lbtafxapp E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.1
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.danikula.videocache.ProxyCacheException: Error using file /storage/emulated/0/lbtafx/video/cache/dd23c41711bee3d2fcfcdcacca61df7e.mp4 as disc cache. Version: 2.7.1
        at com.danikula.videocache.file.FileCache.<init>(FileCache.java:39)
        at com.danikula.videocache.HttpProxyCacheServerClients.newHttpProxyCache(HttpProxyCacheServerClients.java:83)
        at com.danikula.videocache.HttpProxyCacheServerClients.startProcessRequest(HttpProxyCacheServerClients.java:49)
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:39)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.io.IOException: Directory /storage/emulated/0/lbtafx/video/cache can't be created
        at com.danikula.videocache.file.Files.makeDir(Files.java:33)
        at com.danikula.videocache.file.FileCache.<init>(FileCache.java:34)
        at com.danikula.videocache.HttpProxyCacheServerClients.newHttpProxyCache(HttpProxyCacheServerClients.java:83) 
        at com.danikula.videocache.HttpProxyCacheServerClients.startProcessRequest(HttpProxyCacheServerClients.java:49) 
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:39) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-08-25 12:40:02.064 10273-10671/com.hldm.lbtafxapp I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2

**Comment by Jay-YaoJie** [comment]
https://github.com/danikula/AndroidVideoCache/issues/134

**Comment by zhangyuxgg** [comment]
我给您发邮件了，麻烦回复我一下，谢谢了！

**Comment by zhangyuxgg** [comment]
我给您发邮件了，麻烦回复我一下，谢谢了！
