### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" 

### ISSUE THREAD

**Issue by jdpxiaoming** [danikula/AndroidVideoCache#275]
when use androidx and publish an release apk . 
it appear crash every times .

**Comment by jdpxiaoming** [comment]
add the `-keep class androidx.core.app.CoreComponentFactory { *; }`
on proguard .
and now error:

```goovy
2020-06-05 15:40:27.270 ? E/BitmapFactory: Unable to decode stream: java.lang.NullPointerException
2020-06-05 15:40:27.302 ? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kedacom.ovopark, PID: 20431
    java.lang.IncompatibleClassChangeError: Expected 'java.lang.String j.d.c.a' to be a instance field rather than a static field (declaration of 'j.d.c.a' appears in /data/app/com.kedacom.ovopark-SyLvjq_-nOIncTMUB5YWsw==/base.apk!classes9.dex)
        at j.d.c.a.<init>(AndroidLoggerAdapter.java:2)
        at j.d.c.b.a(AndroidLoggerFactory.java:3)
        at j.d.d.a(LoggerFactory.java:28)
        at com.danikula.videocache.StorageUtils.<clinit>(StorageUtils.java:1)
        at com.danikula.videocache.StorageUtils.getIndividualCacheDirectory(Unknown Source:0)
        at com.danikula.videocache.HttpProxyCacheServer$Builder.<init>(HttpProxyCacheServer.java:3)
        at com.kedacom.ovopark.BaseApplication.B(BaseApplication.java:1)
        at com.kedacom.ovopark.BaseApplication.k(BaseApplication.java:2)
```

**Comment by jdpxiaoming** [comment]
finally, i resolve it by disable minifyEnabled and shrinkResources 

```groovy
 buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            ...
      }
}
```
