### ISSUE TITLE
Android L: NullPointerException on HttpURLConnection.disconnect

### ISSUE THREAD

**Issue by arthurpalves** [danikula/AndroidVideoCache#29]
This is a **multithreading issue** as seen here https://github.com/square/okio/issues/79
`HttpURLConnection` on Lollipop uses an outdated version of `okhttp`, which doesn't have the fix.

A quicker "fix" is to handle the `NullPointerException` on `HttpUrlSource.read`**(HttpUrlSource.java:89)** and `HttpUrlSource.close`**(HttpUrlSource.java:79)**

I was willing to do it, but I can't even compile the library on Android Studio:
```
Error:Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1
```

Logs:

```
E/ProxyCache﹕ ProxyCache error
    java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
            at com.android.okio.OkBuffer.write(OkBuffer.java:574)
            at com.android.okio.OkBuffer.read(OkBuffer.java:610)
            at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:56)
            at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:465)
            at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:174)
            at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
            at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:89)
            at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:125)
            at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
            at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:178)
            at java.lang.Thread.run(Thread.java:818)


11-01 10:15:51.916  19061-25773/com.sample.sample.debuggable E/AndroidRuntime﹕ FATAL EXCEPTION: Source reader for HttpUrlSource{url='https://www.qviky.com/sample.mp4}
    Process: com.sample.sample.debuggable, PID: 19061
    java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
            at com.android.okio.OkBuffer.write(OkBuffer.java:574)
            at com.android.okio.OkBuffer.read(OkBuffer.java:610)
            at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:56)
            at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:465)
            at com.android.okhttp.internal.Util.skipAll(Util.java:227)
            at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:235)
            at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:487)
            at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
            at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:574)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
            at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
            at com.danikula.videocache.HttpUrlSource.close(HttpUrlSource.java:79)
            at com.danikula.videocache.ProxyCache.closeSource(ProxyCache.java:159)
            at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:140)
            at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
            at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:178)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by arthurpalves** [comment]
I built successfully and created a pull request to solve this. Closing issue.

**Comment by Murtaza0xFF** [comment]
@arthurpalves what was the problem? I've been getting the same error?

**Comment by arthurpalves** [comment]
@Murtaza0xFF Just a NPE, a catch was implemented by @danikula already, but to successfully solve the problem I compiled OkHttp 2.5.0 and used their `HttpUrlConnectionImpl` instead of Android's default `HttpUrlConnection`.

**Comment by danikula** [comment]
Previous fix was incorrect. Real fix [here](https://github.com/danikula/AndroidVideoCache/commit/6c996ea66c857cf202c03835594ee6344b5fd3e0)
