### ISSUE TITLE
Error Pinging Server 

### ISSUE THREAD

**Issue by bhumikash-tech** [danikula/AndroidVideoCache#304]
I am leaving my issue here as told in Logcat. Please tell me the valid solution as I have already tried to add android:usesCleartextTraffic="true" , <uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />  and  android:networkSecurityConfig="@xml/network_config" in manifest file, but still facing same crashing issue. 
 I am facing below error:
If you see this message, please, report at https://github.com/danikula/AndroidVideoCache/issues/134. Default proxies are: [DIRECT]
    com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, report at https://github.com/danikula/AndroidVideoCache/issues/134. Default proxies are: [DIRECT]. Version: 2.7.1
        at com.danikula.videocache.Pinger.ping(Pinger.java:73)
        at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:185)
        at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:122)
        at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:103)
        at com.musicApp.raask.utils.CacheUtil.prefetchContents(CacheUtil.java:23)
        at com.musicApp.raask.utils.CacheUtil.lambda$prefetchOrTimeout$1(CacheUtil.java:35)
        at com.musicApp.raask.utils.-$$Lambda$CacheUtil$9G0FsUaR3XsEHFV5ICLOI-UGRXI.run(Unknown Source:4)

**Comment by EbelloImbox** [comment]
Any help? I have the same issue

**Comment by 24suixinsuoyu** [comment]
```android:usesCleartextTraffic="true"```, it works for me.

Also, update the compileSdk to 31? Try this, maybe it works.
