### ISSUE TITLE
Is it possible to move the library to the mavenCentral repository?

### ISSUE THREAD

**Issue by AlejandroImbox** [danikula/AndroidVideoCache#308]
Since jCenter has been left in a read-only repository, I would like to be able to continue using this great library.
And I wanted to know if it could be uploaded to the maven central repository.
thank you very much, best regards @danikula

**Comment by ghost** [comment]
@danikula Same issue here. We are relying on react-native-video-cache library that tries and fails to pull com.danikula:videocache:2.7.1 from jcenter repo that is now down

**Comment by onozuka** [comment]
I have succeeded in creating aar by taking temporary measures locally for v2.7.0.
I hope someone can fix the remaining issues and make a pull request.

FYI:
Modify Commit:
https://github.com/danikula/AndroidVideoCache/commit/8acbb01f6ed1bd3fdb665291454aa6d3c8168920

```
     repositories {
-        jcenter()
+        google()
+        mavenCentral()
     }
```

interim measures:
Temporarily modified for older tools and local environment.
Exclude the sample build.

## problem logs

gradle sync error log
```
Could not resolve all files for configuration ':app:developDebugCompileClasspath'.
> Could not find AndroidVideoCache.aar (com.github.danikula:AndroidVideoCache:v2.7.0).
  Searched in the following locations:
      https://jitpack.io/com/github/danikula/AndroidVideoCache/v2.7.0/AndroidVideoCache-v2.7.0.aar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

https://jitpack.io/com/github/danikula/AndroidVideoCache/v2.7.0/AndroidVideoCache-v2.7.0.aar
When accessed with a browser. `Build failed. See the log at jitpack.io`

https://jitpack.io/com/github/danikula/AndroidVideoCache/v2.7.0/build.log
When accessed with a browser. `Could not GET 'https://dl.bintray.com/alexeydanilov/maven/com/danikula/android-garden/2.1.4/android-garden-2.1.4.pom'. Received status code 502 from server: Bad Gateway`

**Comment by zhigang1992** [comment]
@GregVes react-native-video-cache now vendor this aab directly.

**Comment by a-mar-se** [comment]
The app can't be built. When trying "npx react-native run-android" returns this error:
Could not find com.danikula:videocache:2.7.1.

**Comment by rpluniversity** [comment]
Same here

**Comment by Yasser-G** [comment]
any update about this issue?

**Comment by nilesh-simform** [comment]
Any updates on this issue please? facing similar issue @danikula

**Comment by wimramuha** [comment]
Also encountered same issue after trying react-native-video-cache @danikula

**Comment by nihp** [comment]
Any solution for the above issue. i am using this SDK. Any solution for this

```
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find videocache-2.7.1.aar (com.danikula:videocache:2.7.1).
Searched in the following locations:
    https://jcenter.bintray.com/com/danikula/videocache/2.7.1/videocache-2.7.1.aar
    https://jcenter.bintray.com/com/danikula/videocache/2.7.1/videocache-2.7.1.jar
	at org.gradle.internal.resolve.result.DefaultBuildableArtifactFileResolveResult.notFound(DefaultBuildableArtifactFileResolveResult.java:28)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifactFromCache(CachingModuleComponentRepository.java:338)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:291)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.lambda$resolveArtifact$12(ErrorHandlingModuleComponentRepository.java:172)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.tryResolveAndMaybeBlacklist(ErrorHandlingModuleComponentRepository.java:227)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.performOperationWithRetries(ErrorHandlingModuleComponentRepository.java:194)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveArtifact(ErrorHandlingModuleComponentRepository.java:170)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.resolveArtifactLater(RepositoryChainArtifactResolver.java:74)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.lambda$resolveArtifact$0(RepositoryChainArtifactResolver.java:64)
	at org.gradle.internal.model.CalculatedValueContainerFactory$SupplierBackedCalculator.calculateValue(CalculatedValueContainerFactory.java:65)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:229)
	at org.gradle.internal.Try.ofFailable(Try.java:41)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.attachValue(CalculatedValueContainer.java:224)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:197)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:188)
	at org.gradle.api.internal.artifacts.transform.TransformingAsyncArtifactListener$TransformedArtifact.finalizeValue(TransformingAsyncArtifactListener.java:193)
	at org.gradle.api.internal.artifacts.transform.TransformingAsyncArtifactListener$TransformedArtifact.run(TransformingAsyncArtifactListener.java:147)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$QueueWorker.execute(DefaultBuildOperationExecutor.java:238)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:272)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.doRunBatch(DefaultBuildOperationQueue.java:253)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$0(DefaultBuildOperationQueue.java:238)
	at org.gradle.internal.resources.AbstractResourceLockRegistry.whileDisallowingLockChanges(AbstractResourceLockRegistry.java:50)
	at org.gradle.internal.work.DefaultWorkerLeaseService.whileDisallowingProjectLockChanges(DefaultWorkerLeaseService.java:236)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$1(DefaultBuildOperationQueue.java:238)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:224)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:192)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

==============================================================================

```
