### ISSUE TITLE
播放苹果手机b站客户端直播视频的dlna投屏链接出现error

### ISSUE THREAD

**Issue by unnoPlayer** [danikula/AndroidVideoCache#315]
当url设置为苹果手机b站客户端直播视频的dlna投屏的链接后，出现了error，具体log如下：
D/IJKMEDIA: IjkMediaPlayer_native_init
D/IJKMEDIA: IjkMediaPlayer_native_setup
I/IJKMEDIA: av_version_info: 97349ff2
I/IJKMEDIA: ijk_version_info: 97349ff2
D/IJKMEDIA: ffpipeline_create_from_android()
D/IJKMEDIA: ijkmp_set_inject_opaque(0x29a2)
D/IJKMEDIA: ijkmp_set_inject_opaque()=void
D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x29a2)
D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
D/IJKMEDIA: IjkMediaPlayer_setOptionLong
D/IJKMEDIA: IjkMediaPlayer_setOption
D/IJKMEDIA: IjkMediaPlayer_setOption
D/IJKMEDIA: IjkMediaPlayer_setOptionLong
D/IJKMEDIA: IjkMediaPlayer_setOptionLong
D/IJKMEDIA: IjkMediaPlayer_reset
D/IJKMEDIA: IjkMediaPlayer_release
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: ijkmp_shutdown_l()=void
D/IJKMEDIA: IjkMediaPlayer_native_setup
I/IJKMEDIA: av_version_info: 97349ff2
I/IJKMEDIA: ijk_version_info: 97349ff2
D/IJKMEDIA: ffpipeline_create_from_android()
D/IJKMEDIA: ijkmp_set_inject_opaque(0x29fa)
D/IJKMEDIA: ijkmp_set_inject_opaque()=void
D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x29fa)
D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
D/IJKMEDIA: ijkmp_dec_ref(): ref=0
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: ijkmp_shutdown_l()=void
I/Pinger: Ping response: `ping ok`, pinged? true
I/HttpProxyCacheServer: Proxy cache server started. Is it alive? true
I/Pinger: Ping response: `ping ok`, pinged? true
D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
V/IJKMEDIA: setDataSource: path http://127.0.0.1:43433/http%3A%2F%2F119.84.174.8%2Flive-bvc%2F151195%2Flive_28552103_12565112_1500.flv%3Fexpires%3D1669370899%26pt%3Dios%26deadline%3D1669370899%26len%3D0%26oi%3D1901585047%26platform%3Dios%26qn%3D64%26trid%3D1000c6be16fe30ac4229a22734051e5d0862%26uipk%3D100%26uipv%3D100%26nbs%3D1%26uparams%3Dcdn%2Cdeadline%2Clen%2Coi%2Cplatform%2Cqn%2Ctrid%2Cuipk%2Cuipv%2Cnbs%26cdn%3Dcn-gotcha01%26upsig%3Da3d76969de4923f17897df218b0dd9dc%26sk%3D1304f646dfeb4df8b6e7ff33c167d3ad899b33eab284038eff41ce83ae9a8a1f%26p2p_type%3D8192%26src%3D57345%26sl%3D2%26free_type%3D0%26sid%3Dcn-cq-ct-01-07%26chash%3D1%26sche%3Dban%26score%3D7%26usgroup%3Deg%26pp%3Dsrt%26machinezone%3Dylf%26source%3Donetier%26site%3Dc80af6381fa993ea2aca07260e96ede1%26order%3D1%26bili_room_id%3D24780388%26_nva_ext_%3D
D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:43433/http%3A%2F%2F119.84.174.8%2Flive-bvc%2F151195%2Flive_28552103_12565112_1500.flv%3Fexpires%3D1669370899%26pt%3Dios%26deadline%3D1669370899%26len%3D0%26oi%3D1901585047%26platform%3Dios%26qn%3D64%26trid%3D1000c6be16fe30ac4229a22734051e5d0862%26uipk%3D100%26uipv%3D100%26nbs%3D1%26uparams%3Dcdn%2Cdeadline%2Clen%2Coi%2Cplatform%2Cqn%2Ctrid%2Cuipk%2Cuipv%2Cnbs%26cdn%3Dcn-gotcha01%26upsig%3Da3d76969de4923f17897df218b0dd9dc%26sk%3D1304f646dfeb4df8b6e7ff33c167d3ad899b33eab284038eff41ce83ae9a8a1f%26p2p_type%3D8192%26src%3D57345%26sl%3D2%26free_type%3D0%26sid%3Dcn-cq-ct-01-07%26chash%3D1%26sche%3Dban%26score%3D7%26usgroup%3Deg%26pp%3Dsrt%26machinezone%3Dylf%26source%3Donetier%26site%3Dc80af6381fa993ea2aca07260e96ede1%26order%3D1%26bili_room_id%3D24780388%26_nva_ext_%3D")
D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:43433/http%3A%2F%2F119.84.174.8%2Flive-bvc%2F151195%2Flive_28552103_12565112_1500.flv%3Fexpires%3D1669370899%26pt%3Dios%26deadline%3D1669370899%26len%3D0%26oi%3D1901585047%26platform%3Dios%26qn%3D64%26trid%3D1000c6be16fe30ac4229a22734051e5d0862%26uipk%3D100%26uipv%3D100%26nbs%3D1%26uparams%3Dcdn%2Cdeadline%2Clen%2Coi%2Cplatform%2Cqn%2Ctrid%2Cuipk%2Cuipv%2Cnbs%26cdn%3Dcn-gotcha01%26upsig%3Da3d76969de4923f17897df218b0dd9dc%26sk%3D1304f646dfeb4df8b6e7ff33c167d3ad899b33eab284038eff41ce83ae9a8a1f%26p2p_type%3D8192%26src%3D57345%26sl%3D2%26free_type%3D0%26sid%3Dcn-cq-ct-01-07%26chash%3D1%26sche%3Dban%26score%3D7%26usgroup%3Deg%26pp%3Dsrt%26machinezone%3Dylf%26source%3Donetier%26site%3Dc80af6381fa993ea2aca07260e96ede1%26order%3D1%26bili_room_id%3D24780388%26_nva_ext_%3D")=0
D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffd29120)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffd29120)=void
D/IJKMEDIA: IjkMediaPlayer_setOptionLong
D/IJKMEDIA: IjkMediaPlayer_setOptionLong
D/IJKMEDIA: IjkMediaPlayer_prepareAsync
D/IJKMEDIA: ijkmp_prepare_async()
I/IJKMEDIA: ===== versions =====
I/IJKMEDIA: ijkplayer    : 97349ff2
I/IJKMEDIA: FFmpeg       : 97349ff2
I/IJKMEDIA: libavutil    : 55.78.100
I/IJKMEDIA: libavcodec   : 57.107.100
I/IJKMEDIA: libavformat  : 57.83.100
I/IJKMEDIA: libswscale   : 4.8.100
I/IJKMEDIA: libswresample: 2.9.100
I/IJKMEDIA: ===== options =====
I/IJKMEDIA: player-opts : framedrop                    = 10
I/IJKMEDIA: player-opts : enable-accurate-seek         = 1
I/IJKMEDIA: player-opts : soundtouch                   = 1
I/IJKMEDIA: format-opts : ijkapplication               = -155507376
I/IJKMEDIA: format-opts : ijkiomanager                 = -956212096
I/IJKMEDIA: ===================
D/IJKMEDIA: ijkmp_prepare_async()=0
I/IJKMEDIA: SDL_RunThread: [13887] ff_msg_loop
D/IJKMEDIA: message_loop
D/IJKMEDIA: FFP_MSG_FLUSH:
I/IJKMEDIA: SDL_RunThread: [13888] ff_vout
I/IJKMEDIA: SDL_RunThread: [13889] ff_read
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074

E/HttpUrlSource: Error fetching info from http://119.84.174.8/live-bvc/151195/live_28552103_12565112_1500.flv?expires=1669370899&pt=ios&deadline=1669370899&len=0&oi=1901585047&platform=ios&qn=64&trid=1000c6be16fe30ac4229a22734051e5d0862&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=a3d76969de4923f17897df218b0dd9dc&sk=1304f646dfeb4df8b6e7ff33c167d3ad899b33eab284038eff41ce83ae9a8a1f&p2p_type=8192&src=57345&sl=2&free_type=0&sid=cn-cq-ct-01-07&chash=1&sche=ban&score=7&usgroup=eg&pp=srt&machinezone=ylf&source=onetier&site=c80af6381fa993ea2aca07260e96ede1&order=1&bili_room_id=24780388&_nva_ext_=
    java.io.FileNotFoundException: http://119.84.174.8/live-bvc/151195/live_28552103_12565112_1500.flv?expires=1669370899&pt=ios&deadline=1669370899&len=0&oi=1901585047&platform=ios&qn=64&trid=1000c6be16fe30ac4229a22734051e5d0862&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=a3d76969de4923f17897df218b0dd9dc&sk=1304f646dfeb4df8b6e7ff33c167d3ad899b33eab284038eff41ce83ae9a8a1f&p2p_type=8192&src=57345&sl=2&free_type=0&sid=cn-cq-ct-01-07&chash=1&sche=ban&score=7&usgroup=eg&pp=srt&machinezone=ylf&source=onetier&site=c80af6381fa993ea2aca07260e96ede1&order=1&bili_room_id=24780388&_nva_ext_=
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:141)
        at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:70)
        at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:62)
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:40)
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

E/HttpUrlSource: Error fetching info from http://119.84.174.8/live-bvc/151195/live_28552103_12565112_1500.flv?expires=1669370899&pt=ios&deadline=1669370899&len=0&oi=1901585047&platform=ios&qn=64&trid=1000c6be16fe30ac4229a22734051e5d0862&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=a3d76969de4923f17897df218b0dd9dc&sk=1304f646dfeb4df8b6e7ff33c167d3ad899b33eab284038eff41ce83ae9a8a1f&p2p_type=8192&src=57345&sl=2&free_type=0&sid=cn-cq-ct-01-07&chash=1&sche=ban&score=7&usgroup=eg&pp=srt&machinezone=ylf&source=onetier&site=c80af6381fa993ea2aca07260e96ede1&order=1&bili_room_id=24780388&_nva_ext_=
    java.io.FileNotFoundException: http://119.84.174.8/live-bvc/151195/live_28552103_12565112_1500.flv?expires=1669370899&pt=ios&deadline=1669370899&len=0&oi=1901585047&platform=ios&qn=64&trid=1000c6be16fe30ac4229a22734051e5d0862&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=a3d76969de4923f17897df218b0dd9dc&sk=1304f646dfeb4df8b6e7ff33c167d3ad899b33eab284038eff41ce83ae9a8a1f&p2p_type=8192&src=57345&sl=2&free_type=0&sid=cn-cq-ct-01-07&chash=1&sche=ban&score=7&usgroup=eg&pp=srt&machinezone=ylf&source=onetier&site=c80af6381fa993ea2aca07260e96ede1&order=1&bili_room_id=24780388&_nva_ext_=
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:141)
        at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:70)
        at com.danikula.videocache.HttpProxyCache.isUseCache(HttpProxyCache.java:52)
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:44)
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
E/ProxyCache: ProxyCache error
    com.danikula.videocache.ProxyCacheException: Error opening connection for http://119.84.174.8/live-bvc/151195/live_28552103_12565112_1500.flv?expires=1669370899&pt=ios&deadline=1669370899&len=0&oi=1901585047&platform=ios&qn=64&trid=1000c6be16fe30ac4229a22734051e5d0862&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=a3d76969de4923f17897df218b0dd9dc&sk=1304f646dfeb4df8b6e7ff33c167d3ad899b33eab284038eff41ce83ae9a8a1f&p2p_type=8192&src=57345&sl=2&free_type=0&sid=cn-cq-ct-01-07&chash=1&sche=ban&score=7&usgroup=eg&pp=srt&machinezone=ylf&source=onetier&site=c80af6381fa993ea2aca07260e96ede1&order=1&bili_room_id=24780388&_nva_ext_= with offset 0. Version: 2.7.1
        at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:85)
        at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123)
        at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
        at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.FileNotFoundException: http://119.84.174.8/live-bvc/151195/live_28552103_12565112_1500.flv?expires=1669370899&pt=ios&deadline=1669370899&len=0&oi=1901585047&platform=ios&qn=64&trid=1000c6be16fe30ac4229a22734051e5d0862&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=a3d76969de4923f17897df218b0dd9dc&sk=1304f646dfeb4df8b6e7ff33c167d3ad899b33eab284038eff41ce83ae9a8a1f&p2p_type=8192&src=57345&sl=2&free_type=0&sid=cn-cq-ct-01-07&chash=1&sche=ban&score=7&usgroup=eg&pp=srt&machinezone=ylf&source=onetier&site=c80af6381fa993ea2aca07260e96ede1&order=1&bili_room_id=24780388&_nva_ext_=
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:80)
        at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123) 
        at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19) 
        at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187) 
        at java.lang.Thread.run(Thread.java:919) 
E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.1
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.danikula.videocache.ProxyCacheException: Error reading source 1 times. Version: 2.7.1
        at com.danikula.videocache.ProxyCache.checkReadSourceErrorsCount(ProxyCache.java:59)
        at com.danikula.videocache.ProxyCache.read(ProxyCache.java:45)
        at com.danikula.videocache.HttpProxyCache.responseWithCache(HttpProxyCache.java:79)
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:45)
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:236)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:340) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
E/IJKMEDIA: http://127.0.0.1:43433/http%3A%2F%2F119.84.174.8%2Flive-bvc%2F151195%2Flive_28552103_12565112_1500.flv%3Fexpires%3D1669370899%26pt%3Dios%26deadline%3D1669370899%26len%3D0%26oi%3D1901585047%26platform%3Dios%26qn%3D64%26trid%3D1000c6be16fe30ac4229a22734051e5d0862%26uipk%3D100%26uipv%3D100%26nbs%3D1%26uparams%3Dcdn%2Cdeadline%2Clen%2Coi%2Cplatform%2Cqn%2Ctrid%2Cuipk%2Cuipv%2Cnbs%26cdn%3Dcn-gotcha01%26upsig%3Da3d76969de4923f17897df218b0dd9dc%26sk%3D1304f646dfeb4df8b6e7ff33c167d3ad899b33eab284038eff41ce83ae9a8a1f%26p2p_type%3D8192%26src%3D57345%26sl%3D2%26free_type%3D0%26sid%3Dcn-cq-ct-01-07%26chash%3D1%26sche%3Dban%26score%3D7%26usgroup%3Deg%26pp%3Dsrt%26machinezone%3Dylf%26source%3Donetier%26site%3Dc80af6381fa993ea2aca07260e96ede1%26order%3D1%26bili_room_id%3D24780388%26_nva_ext_%3D: End of file
D/IJKMEDIA: FFP_MSG_ERROR: 0
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13889]
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
D/IJKMEDIA: IjkMediaPlayer_reset
D/IJKMEDIA: IjkMediaPlayer_release
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: message_loop exit
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13887]
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13888]
D/IJKMEDIA: ijkmp_shutdown_l()=void
D/IJKMEDIA: IjkMediaPlayer_native_setup
I/IJKMEDIA: av_version_info: 97349ff2
I/IJKMEDIA: ijk_version_info: 97349ff2
D/IJKMEDIA: ffpipeline_create_from_android()
D/IJKMEDIA: ijkmp_set_inject_opaque(0x2a02)
D/IJKMEDIA: ijkmp_set_inject_opaque()=void
D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x2a02)
D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
D/IJKMEDIA: ijkmp_dec_ref(): ref=0
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: ijkmp_shutdown_l()=void

D/IJKMEDIA: IjkMediaPlayer_reset
D/IJKMEDIA: IjkMediaPlayer_release
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: ijkmp_shutdown_l()=void
D/IJKMEDIA: IjkMediaPlayer_native_setup
I/IJKMEDIA: av_version_info: 97349ff2
I/IJKMEDIA: ijk_version_info: 97349ff2
D/IJKMEDIA: ffpipeline_create_from_android()
D/IJKMEDIA: ijkmp_set_inject_opaque(0x2a42)
D/IJKMEDIA: ijkmp_set_inject_opaque()=void
D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x2a42)
D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
D/IJKMEDIA: ijkmp_dec_ref(): ref=0
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: ijkmp_shutdown_l()=void
D/IJKMEDIA: IjkMediaPlayer_release
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: ijkmp_shutdown_l()=void
D/IJKMEDIA: ijkmp_dec_ref(): ref=0
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: ijkmp_shutdown_l()=void

这个问题是使用苹果手机的b站直播视频的dlna投屏的链接才会出现，而且是有的直播视频会有的不会。
请问该如何解决？

**Comment by shishaopo** [comment]
> 

你这用dns解析ip了吧

**Comment by unnoPlayer** [comment]
> > 
> 
> 你这用dns解析ip了吧

直接用的，没做任何改动
