### ISSUE TITLE
SocketException: Socket closed on Android L

### ISSUE THREAD

**Issue by joluet** [danikula/AndroidVideoCache#37]
For some reason on api level 21 and 22 some streams can't be cached. The media player seems to do some range requests and then the proxy cache tries to access a socket that has been closed.
This is not happening on api level 23. Any ideas?

```
I/ProxyCache: Content info for `http://feedproxy.google.com/~r/modtv/podcast/~5/dr4aovVf3pQ/CHANEL_S16.m4v`: mime: video/mp4, content-length: 189174193
D/ProxyCache: buffered 2
D/ProxyCache: Open connection  with offset 3958950 to http://feedproxy.google.com/~r/modtv/podcast/~5/dr4aovVf3pQ/CHANEL_S16.m4v
D/ProxyCache: buffered 2
D/ProxyCache: Accept new socket Socket[address=/127.0.0.1,port=47998,localPort=49705]
I/ProxyCache: Request to cache proxy:GetRequest{rangeOffset=188912049, partial=true, uri='http%3A%2F%2Ffeedproxy.google.com%2F%7Er%2Fmodtv%2Fpodcast%2F%7E5%2Fdr4aovVf3pQ%2FCHANEL_S16.m4v'}
D/ProxyCache: Open connection  with offset 188912049 to http://feedproxy.google.com/~r/modtv/podcast/~5/dr4aovVf3pQ/CHANEL_S16.m4v
D/ProxyCache: Accept new socket Socket[address=/127.0.0.1,port=39932,localPort=49705]
I/ProxyCache: Request to cache proxy:GetRequest{rangeOffset=188912049, partial=true, uri='http%3A%2F%2Ffeedproxy.google.com%2F%7Er%2Fmodtv%2Fpodcast%2F%7E5%2Fdr4aovVf3pQ%2FCHANEL_S16.m4v'}
D/ProxyCache: Open connection  with offset 188912049 to http://feedproxy.google.com/~r/modtv/podcast/~5/dr4aovVf3pQ/CHANEL_S16.m4v
D/ProxyCache: Accept new socket Socket[address=/127.0.0.1,port=42035,localPort=49705]
I/ProxyCache: Request to cache proxy:GetRequest{rangeOffset=188912049, partial=true, uri='http%3A%2F%2Ffeedproxy.google.com%2F%7Er%2Fmodtv%2Fpodcast%2F%7E5%2Fdr4aovVf3pQ%2FCHANEL_S16.m4v'}
D/ProxyCache: Open connection  with offset 188912049 to http://feedproxy.google.com/~r/modtv/podcast/~5/dr4aovVf3pQ/CHANEL_S16.m4v
D/ProxyCache: Closing socket… Socket is closed by client.
D/ProxyCache: Releasing input stream… Socket is closed by client.
D/ProxyCache: Opened connections: 5
D/ProxyCache: Closing socket… Socket is closed by client.
D/ProxyCache: Releasing input stream… Socket is closed by client.
D/ProxyCache: Opened connections: 4
D/ProxyCache: Closing socket… Socket is closed by client.
D/ProxyCache: Releasing input stream… Socket is closed by client.
D/ProxyCache: Opened connections: 3
E/ProxyCache: ProxyCache error
com.danikula.videocache.ProxyCacheException: Error reading data from http://feedproxy.google.com/~r/modtv/podcast/~5/dr4aovVf3pQ/CHANEL_S16.m4v
at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:98)
at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:126)
at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:179)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketException: Socket closed
at libcore.io.Posix.recvfromBytes(Native Method)
at libcore.io.Posix.recvfrom(Posix.java:185)
at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
at okio.Okio$2.read(Okio.java:139)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
at okio.RealBufferedSource.read(RealBufferedSource.java:50)
at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:94)
at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:126) 
at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19) 
at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:179) 
at java.lang.Thread.run(Thread.java:818) 
D/ProxyCache: Opened connections: 2
```

**Comment by liyzay** [comment]
I think I might have found the reason,I posted [here](https://github.com/danikula/AndroidVideoCache/issues/43)
You should change the HttpProxyCache.responseWithoutCache() method to like this :
> private void responseWithoutCache(OutputStream out, long offset) throws ProxyCacheException, IOException {
	    HttpUrlSource newSource = new HttpUrlSource(this.source);
	    try {
            newSource.open((int) offset);
            byte[] buffer = new byte[DEFAULT_BUFFER_SIZE];
            int readBytes;
            while ((readBytes = newSource.read(buffer)) != -1) {
                out.write(buffer, 0, readBytes);
                offset += readBytes;
            }
            out.flush();
        } finally {
		    newSource.close();
        }
    }

**Comment by shaopx** [comment]
try this
https://github.com/danikula/AndroidVideoCache/pull/70

**Comment by danikula** [comment]
Duplicates [43](https://github.com/danikula/AndroidVideoCache/issues/37)

**Comment by danikula** [comment]
Fixed [here](https://github.com/danikula/AndroidVideoCache/commit/6c996ea66c857cf202c03835594ee6344b5fd3e0)
