### ISSUE TITLE
issue in llollipop when maxsizecache   is overcome

### ISSUE THREAD

**Issue by gielDevelop** [danikula/AndroidVideoCache#38]
```
12-18 00:19:56.867 11141-11338/com.describeme D/ProxyCache: Accept new socket Socket[address=/127.0.0.1,port=60658,localPort=57387]
12-18 00:20:06.869 11141-11398/com.describeme E/ProxyCache: Error fetching info from http://127.0.0.1:57387/http%3A%2F%2F127.0.0.1%3A57387%2Fhttp%253A%252F%252F127.0.0.1%253A57387%252Fhttps%25253A%25252F%25252Fd1yibi23zrwr5k.cloudfront.net%25252Fvid%25252F22%25252Fprofile_videos%25252FMOBILE_480TC_20151218031830_94df693a-af5f-4179-a66c-581950408c95.mp4
java.net.SocketTimeoutException
at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
at com.android.okio.Okio$2.read(Okio.java:113)
at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:147)
at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:94)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:138)
at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:108)
at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:53)
at com.danikula.videocache.HttpProxyCache.isUseCache(HttpProxyCache.java:51)
at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:43)
at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:221)
at com.danikula.videocache.HttpProxyCacheServer.access$300(HttpProxyCacheServer.java:55)
at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:331)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by danikula** [comment]
@gielDevelop you use library in incorrect way.
`http://127.0.0.1:57387/http%3A%2F%2F127.0.0.1%3A57387%2Fhttp%253A%252F%252F127.0.0.1%253A57387%252Fhttps%25253A%25252F%25252Fd1yibi23zrwr5k.cloudfront.net%25252Fvid%25252F22%25252Fprofile_videos%25252FMOBILE_480TC_20151218031830_94df693a-af5f-4179-a66c-581950408c95.mp4`

You proxied url few times. It means for single url you will have few cached files.
