### ISSUE TITLE
NPE: causing app to crash on start up

### ISSUE THREAD

**Issue by jsho32** [danikula/AndroidVideoCache#39]
java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
	at com.android.okio.OkBuffer.write(OkBuffer.java:574)
	at com.android.okio.OkBuffer.read(OkBuffer.java:610)
	at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:53)
	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
	at com.android.okhttp.internal.Util.skipAll(Util.java:227)
	at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:212)
	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:464)
	at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
	at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:433)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
	at com.danikula.videocache.HttpUrlSource.close(HttpUrlSource.java:79)
	at com.danikula.videocache.ProxyCache.closeSource(ProxyCache.java:159)
	at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:140)
	at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
	at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:178)
	at java.lang.Thread.run(Thread.java:818)

So far I have only received crash reports from a single device, an HTC One (m7). According to the user, this prevents the app from opening completely. Is this device not supported? or is there any known workarounds etc?

**Comment by jsho32** [comment]
Appears resolved in version 2.3.4
