### ISSUE TITLE
Using ProxyCache for multiple videos

### ISSUE THREAD

**Issue by FstTeam** [danikula/AndroidVideoCache#4]
hi. i play video, and in OnCompletionListener event i play other video
```java
videoview.setOnCompletionListener(new OnCompletionListener() {

            @Override
            public void onCompletion(final MediaPlayer mp) {
                // TODO Auto-generated method stub

                    videoview.setVideoPath(proxyCache.getUrl());
                    videoview.setZOrderOnTop(false);
                    videoview.requestFocus();
                    videoview.setKeepScreenOn(true);
                    videoview.start();

            }
        });
```
. I see 1 exception:
```
05-13 06:07:12.330: E/ProxyCache(21949): ProxyCache error
05-13 06:07:12.330: E/ProxyCache(21949): com.danikula.videocache.ProxyCacheException: Error processing request
05-13 06:07:12.330: E/ProxyCache(21949): at com.danikula.videocache.HttpProxyCache.processSocket(HttpProxyCache.java:139)
05-13 06:07:12.330: E/ProxyCache(21949): at com.danikula.videocache.HttpProxyCache.access$1(HttpProxyCache.java:131)
05-13 06:07:12.330: E/ProxyCache(21949): at com.danikula.videocache.HttpProxyCache$1.run(HttpProxyCache.java:123)
05-13 06:07:12.330: E/ProxyCache(21949): at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
05-13 06:07:12.330: E/ProxyCache(21949): at java.util.concurrent.FutureTask.run(FutureTask.java:234)
05-13 06:07:12.330: E/ProxyCache(21949): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
05-13 06:07:12.330: E/ProxyCache(21949): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
05-13 06:07:12.330: E/ProxyCache(21949): at java.lang.Thread.run(Thread.java:856)
05-13 06:07:12.330: E/ProxyCache(21949): Caused by: java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
05-13 06:07:12.330: E/ProxyCache(21949): at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:506)
05-13 06:07:12.330: E/ProxyCache(21949): at libcore.io.IoBridge.sendto(IoBridge.java:475)
05-13 06:07:12.330: E/ProxyCache(21949): at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507)
05-13 06:07:12.330: E/ProxyCache(21949): at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
05-13 06:07:12.330: E/ProxyCache(21949): at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
05-13 06:07:12.330: E/ProxyCache(21949): at java.io.BufferedOutputStream.write(BufferedOutputStream.java:131)
05-13 06:07:12.330: E/ProxyCache(21949): at com.danikula.videocache.HttpProxyCache.writeResponse(HttpProxyCache.java:157)
05-13 06:07:12.330: E/ProxyCache(21949): at com.danikula.videocache.HttpProxyCache.processSocket(HttpProxyCache.java:137)
05-13 06:07:12.330: E/ProxyCache(21949): ... 7 more
05-13 06:07:12.330: E/ProxyCache(21949): Caused by: libcore.io.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)
05-13 06:07:12.330: E/ProxyCache(21949): at libcore.io.Posix.sendtoBytes(Native Method)
05-13 06:07:12.330: E/ProxyCache(21949): at libcore.io.Posix.sendto(Posix.java:151)
05-13 06:07:12.330: E/ProxyCache(21949): at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
05-13 06:07:12.330: E/ProxyCache(21949): at libcore.io.IoBridge.sendto(IoBridge.java:473)
05-13 06:07:12.330: E/ProxyCache(21949): ... 13 more
```

**Comment by danikula** [comment]
You should use new proxy instance with new file cache for every new video.

**Comment by FstTeam** [comment]
it mean with every new video, i will  create new proxy, new cache, new HttpUrlSource. And i want to know that i need shutdow old proxy, cache, source? Thanks.

**Comment by danikula** [comment]
Right. You must shutdown previous proxy by calling `proxyCache.shutdown()` to correctly closing and releasing all previous resources. And then for new video you must create new proxy, cache, source.

**Comment by danikula** [comment]
@FstTeam please, close issue as soon as you fix your problem.

**Comment by FstTeam** [comment]
tks your answer. But when i shutdown httpproxy, i see 1 error exception. 
05-15 02:00:45.880  28914-28914/com.player.onsigntv I/ProxyCache﹕ Shutdown proxy
05-15 02:00:45.880  28914-29699/com.player.onsigntv E/ProxyCache﹕ ProxyCache error
    com.danikula.videocache.ProxyCacheException: Error during waiting connection
            at com.danikula.videocache.HttpProxyCache.waitForRequest(HttpProxyCache.java:114)
            at com.danikula.videocache.HttpProxyCache.access$100(HttpProxyCache.java:50)
            at com.danikula.videocache.HttpProxyCache$WaitRequestsRunnable.run(HttpProxyCache.java:237)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.net.SocketException: Socket closed
            at libcore.io.Posix.accept(Native Method)
            at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55)
            at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98)
            at java.net.ServerSocket.implAccept(ServerSocket.java:202)
            at java.net.ServerSocket.accept(ServerSocket.java:127)
            at com.danikula.videocache.HttpProxyCache.waitForRequest(HttpProxyCache.java:109)
            at com.danikula.videocache.HttpProxyCache.access$100(HttpProxyCache.java:50)
            at com.danikula.videocache.HttpProxyCache$WaitRequestsRunnable.run(HttpProxyCache.java:237)
            at java.lang.Thread.run(Thread.java:856)

This is mycode:

try {
				if (cache != null) {
					cache .close();
				}
				if (source != null) {
					source .close();
				}
				if (proxyCache != null) {
					proxyCache .shutdown();
				}
			
		} catch (Exception ex) {
		}
try {
			cache = new FileCache(new File(getExternalCacheDir(),
					obj.getUrl_Play()));
			source = new HttpUrlSource(obj.getUrlDownload());
			proxyCache = new HttpProxyCache(source, cache);
			// proxyCache.setCacheListener(this);
			videoHolder.setVideoPath(proxyCache.getUrl());
			videoHolder.setZOrderOnTop(false);
			videoHolder.requestFocus();
			videoHolder.setKeepScreenOn(true);
			videoHolder.start();

		} catch (ProxyCacheException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();

		}
P/s: My player loop video. Thank you.

**Comment by danikula** [comment]
To release proxy you should call only `proxy.shutdown()`. In closes source and cache internally. 
Error below in log during closing proxy is OK, don't worry.
```
05-15 02:00:45.880  28914-28914/com.player.onsigntv I/ProxyCache﹕ Shutdown proxy
05-15 02:00:45.880  28914-29699/com.player.onsigntv E/ProxyCache﹕ ProxyCache error
    com.danikula.videocache.ProxyCacheException: Error during waiting connection
            at com.danikula.videocache.HttpProxyCache.waitForRequest(HttpProxyCache.java:114)
            at com.danikula.videocache.HttpProxyCache.access$100(HttpProxyCache.java:50)
            at com.danikula.videocache.HttpProxyCache$WaitRequestsRunnable.run(HttpProxyCache.java:237)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.net.SocketException: Socket closed
            at libcore.io.Posix.accept(Native Method)
            at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55)
            at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98)
            at java.net.ServerSocket.implAccept(ServerSocket.java:202)
            at java.net.ServerSocket.accept(ServerSocket.java:127)
            at com.danikula.videocache.HttpProxyCache.waitForRequest(HttpProxyCache.java:109)
            at com.danikula.videocache.HttpProxyCache.access$100(HttpProxyCache.java:50)
            at com.danikula.videocache.HttpProxyCache$WaitRequestsRunnable.run(HttpProxyCache.java:237)
            at java.lang.Thread.run(Thread.java:856)
```

Note new proxy you should use only for **new** videos!
