### ISSUE TITLE
Proxy server isn't pinged

### ISSUE THREAD

**Issue by linsea** [danikula/AndroidVideoCache#47]
hello, I met this error on Android 5.0 when using v.2.3.3
```
Proxy server isn't pinged. Caching doesn't work. If you see this message, please, email me danikula@gmail.com
```
detail log :
```
12-28 17:39:31.910 31345-31345/? I/art: Late-enabling -Xcheck:jni
12-28 17:39:31.960 31345-31345/com.danikula.videocache.sample I/System.out: Sending WAIT chunk
12-28 17:39:33.740 31345-31359/com.danikula.videocache.sample I/art: Debugger is active
12-28 17:39:33.760 31345-31345/com.danikula.videocache.sample I/System.out: Debugger has connected
12-28 17:39:33.760 31345-31345/com.danikula.videocache.sample I/System.out: waiting for debugger to settle...
12-28 17:39:35.370 31345-31345/com.danikula.videocache.sample I/System.out: debugger has settled (1457)
12-28 17:39:35.510 31345-31345/com.danikula.videocache.sample I/View: ssignParent(ViewParent parent) parent is: android.view.ViewRootImpl@13c051c3
12-28 17:39:35.540 31345-31417/com.danikula.videocache.sample I/OpenGLRenderer: Initialized EGL, version 1.4
12-28 17:39:35.590 31345-31345/com.danikula.videocache.sample I/View: ssignParent(ViewParent parent) parent is: android.widget.ListView{34c471f VFED.VC. ......ID 0,146-1080,1719 #7f0b0007 app:id/listView}
12-28 17:39:35.590 31345-31345/com.danikula.videocache.sample I/View: ssignParent(ViewParent parent) parent is: android.widget.ListView{34c471f VFED.VC. ......ID 0,146-1080,1719 #7f0b0007 app:id/listView}
12-28 17:39:35.590 31345-31345/com.danikula.videocache.sample I/View: ssignParent(ViewParent parent) parent is: android.widget.ListView{34c471f VFED.VC. ......ID 0,146-1080,1719 #7f0b0007 app:id/listView}
12-28 17:39:35.600 31345-31345/com.danikula.videocache.sample I/View: ssignParent(ViewParent parent) parent is: android.widget.ListView{34c471f VFED.VC. ......ID 0,146-1080,1719 #7f0b0007 app:id/listView}
12-28 17:39:46.500 31345-31345/com.danikula.videocache.sample W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.danikula.videocache.sample/cache
12-28 17:39:49.180 31345-31345/com.danikula.videocache.sample W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.danikula.videocache.sample/cache
12-28 17:39:49.300 31345-31345/com.danikula.videocache.sample I/ProxyCache: Proxy cache server started. Ping it...
12-28 17:39:49.300 31345-31664/com.danikula.videocache.sample I/System: core_booster, getBoosterConfig = false
12-28 17:39:49.320 31345-31665/com.danikula.videocache.sample I/System: core_booster, getBoosterConfig = false
12-28 17:39:49.320 31345-31665/com.danikula.videocache.sample I/System.out: [CDS]rx timeout:0
12-28 17:39:49.320 31345-31665/com.danikula.videocache.sample I/System.out: [socket][0] connection /172.17.10.81:1311;LocalPort=58822(0)
12-28 17:39:49.320 31345-31665/com.danikula.videocache.sample I/System.out: [CDS]connect[/172.17.10.81:1311]
12-28 17:39:49.340 31345-31665/com.danikula.videocache.sample I/System.out: [CDS]port[58822]
12-28 17:39:49.340 31345-31665/com.danikula.videocache.sample I/System.out: [socket][/192.168.253.57:58822] connected
12-28 17:39:49.510 31345-31345/com.danikula.videocache.sample E/ProxyCache: Error pinging server [attempt: 0, timeout: 200]. 
                                                                            java.util.concurrent.TimeoutException
                                                                                at java.util.concurrent.FutureTask.get(FutureTask.java:176)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.makeSureServerWorks(HttpProxyCacheServer.java:99)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:85)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:71)
                                                                                at com.danikula.videocache.sample.App.newProxy(App.java:21)
                                                                                at com.danikula.videocache.sample.App.getProxy(App.java:17)
                                                                                at com.danikula.videocache.sample.VideoFragment.startVideo(VideoFragment.java:53)
                                                                                at com.danikula.videocache.sample.VideoFragment.afterViewInjected(VideoFragment.java:49)
                                                                                at com.danikula.videocache.sample.VideoFragment_.onViewChanged(VideoFragment_.java:106)
                                                                                at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
                                                                                at com.danikula.videocache.sample.VideoFragment_.onViewCreated(VideoFragment_.java:72)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1097)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
                                                                                at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
                                                                                at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
                                                                                at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
                                                                                at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1224)
                                                                                at android.app.Activity.performStart(Activity.java:6032)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
                                                                                at android.app.ActivityThread.access$1200(ActivityThread.java:152)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5538)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)
12-28 17:39:49.510 31345-31671/com.danikula.videocache.sample I/System: core_booster, getBoosterConfig = false
12-28 17:39:49.510 31345-31671/com.danikula.videocache.sample I/System.out: [CDS]rx timeout:0
12-28 17:39:49.510 31345-31671/com.danikula.videocache.sample I/System.out: [socket][1] connection /172.17.10.81:1311;LocalPort=43725(0)
12-28 17:39:49.510 31345-31671/com.danikula.videocache.sample I/System.out: [CDS]connect[/172.17.10.81:1311]
12-28 17:39:49.520 31345-31671/com.danikula.videocache.sample I/System.out: [CDS]port[43725]
12-28 17:39:49.520 31345-31671/com.danikula.videocache.sample I/System.out: [socket][/192.168.253.57:43725] connected
12-28 17:39:49.910 31345-31345/com.danikula.videocache.sample E/ProxyCache: Error pinging server [attempt: 1, timeout: 400]. 
                                                                            java.util.concurrent.TimeoutException
                                                                                at java.util.concurrent.FutureTask.get(FutureTask.java:176)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.makeSureServerWorks(HttpProxyCacheServer.java:99)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:85)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:71)
                                                                                at com.danikula.videocache.sample.App.newProxy(App.java:21)
                                                                                at com.danikula.videocache.sample.App.getProxy(App.java:17)
                                                                                at com.danikula.videocache.sample.VideoFragment.startVideo(VideoFragment.java:53)
                                                                                at com.danikula.videocache.sample.VideoFragment.afterViewInjected(VideoFragment.java:49)
                                                                                at com.danikula.videocache.sample.VideoFragment_.onViewChanged(VideoFragment_.java:106)
                                                                                at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
                                                                                at com.danikula.videocache.sample.VideoFragment_.onViewCreated(VideoFragment_.java:72)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1097)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
                                                                                at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
                                                                                at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
                                                                                at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
                                                                                at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1224)
                                                                                at android.app.Activity.performStart(Activity.java:6032)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
                                                                                at android.app.ActivityThread.access$1200(ActivityThread.java:152)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5538)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)
12-28 17:39:49.920 31345-31680/com.danikula.videocache.sample I/System: core_booster, getBoosterConfig = false
12-28 17:39:49.930 31345-31680/com.danikula.videocache.sample I/System.out: [CDS]rx timeout:0
12-28 17:39:49.930 31345-31680/com.danikula.videocache.sample I/System.out: [socket][2] connection /172.17.10.81:1311;LocalPort=54341(0)
12-28 17:39:49.930 31345-31680/com.danikula.videocache.sample I/System.out: [CDS]connect[/172.17.10.81:1311]
12-28 17:39:49.950 31345-31680/com.danikula.videocache.sample I/System.out: [CDS]port[54341]
12-28 17:39:49.950 31345-31680/com.danikula.videocache.sample I/System.out: [socket][/192.168.253.57:54341] connected
12-28 17:39:50.460 31345-31665/com.danikula.videocache.sample E/ProxyCache: Error reading ping response
                                                                            com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:42486/ping with offset 0
                                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:66)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55)
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339)
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:831)
                                                                             Caused by: java.io.FileNotFoundException: http://127.0.0.1:42486/ping
                                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
                                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:63)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120) 
                                                                                at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55) 
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339) 
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335) 
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                at java.lang.Thread.run(Thread.java:831) 
12-28 17:39:50.460 31345-31665/com.danikula.videocache.sample I/System.out: [CDS]close[58822]
12-28 17:39:50.460 31345-31665/com.danikula.videocache.sample I/System.out: close [socket][/0.0.0.0:58822]
12-28 17:39:50.600 31345-31671/com.danikula.videocache.sample E/ProxyCache: Error reading ping response
                                                                            com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:42486/ping with offset 0
                                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:66)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55)
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339)
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:831)
                                                                             Caused by: java.io.FileNotFoundException: http://127.0.0.1:42486/ping
                                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
                                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:63)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120) 
                                                                                at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55) 
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339) 
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335) 
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                at java.lang.Thread.run(Thread.java:831) 
12-28 17:39:50.600 31345-31671/com.danikula.videocache.sample I/System.out: [CDS]close[43725]
12-28 17:39:50.600 31345-31671/com.danikula.videocache.sample I/System.out: close [socket][/0.0.0.0:43725]
12-28 17:39:50.720 31345-31345/com.danikula.videocache.sample E/ProxyCache: Error pinging server [attempt: 2, timeout: 800]. 
                                                                            java.util.concurrent.TimeoutException
                                                                                at java.util.concurrent.FutureTask.get(FutureTask.java:176)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.makeSureServerWorks(HttpProxyCacheServer.java:99)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:85)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:71)
                                                                                at com.danikula.videocache.sample.App.newProxy(App.java:21)
                                                                                at com.danikula.videocache.sample.App.getProxy(App.java:17)
                                                                                at com.danikula.videocache.sample.VideoFragment.startVideo(VideoFragment.java:53)
                                                                                at com.danikula.videocache.sample.VideoFragment.afterViewInjected(VideoFragment.java:49)
                                                                                at com.danikula.videocache.sample.VideoFragment_.onViewChanged(VideoFragment_.java:106)
                                                                                at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
                                                                                at com.danikula.videocache.sample.VideoFragment_.onViewCreated(VideoFragment_.java:72)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1097)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
                                                                                at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
                                                                                at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
                                                                                at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
                                                                                at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1224)
                                                                                at android.app.Activity.performStart(Activity.java:6032)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
                                                                                at android.app.ActivityThread.access$1200(ActivityThread.java:152)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5538)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)
12-28 17:39:51.070 31345-31680/com.danikula.videocache.sample E/ProxyCache: Error reading ping response
                                                                            com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:42486/ping with offset 0
                                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:66)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55)
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339)
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:831)
                                                                             Caused by: java.io.FileNotFoundException: http://127.0.0.1:42486/ping
                                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
                                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:63)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120) 
                                                                                at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55) 
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339) 
                                                                                at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335) 
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                at java.lang.Thread.run(Thread.java:831) 
12-28 17:39:51.070 31345-31680/com.danikula.videocache.sample I/System.out: [CDS]close[54341]
12-28 17:39:51.070 31345-31680/com.danikula.videocache.sample I/System.out: close [socket][/0.0.0.0:54341]
12-28 17:39:59.810 31345-31345/com.danikula.videocache.sample E/ProxyCache: Shutdown server… Error pinging server [attempt: 3, timeout: 1600]. If you see this message, please, email me danikula@gmail.com
12-28 17:39:59.810 31345-31345/com.danikula.videocache.sample I/ProxyCache: Shutdown proxy server
12-28 17:39:59.810 31345-31345/com.danikula.videocache.sample I/System.out: [CDS]close[42486]
12-28 17:39:59.810 31345-31664/com.danikula.videocache.sample I/System.out: close [socket][/0.0.0.0:-1]
12-28 17:39:59.820 31345-31664/com.danikula.videocache.sample E/ProxyCache: HttpProxyCacheServer error
                                                                            com.danikula.videocache.ProxyCacheException: Error during waiting connection
                                                                                at com.danikula.videocache.HttpProxyCacheServer.waitForRequest(HttpProxyCacheServer.java:208)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:55)
                                                                                at com.danikula.videocache.HttpProxyCacheServer$WaitRequestsRunnable.run(HttpProxyCacheServer.java:317)
                                                                                at java.lang.Thread.run(Thread.java:831)
                                                                             Caused by: java.net.SocketException: Socket closed
                                                                                at libcore.io.Posix.accept(Native Method)
                                                                                at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
                                                                                at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
                                                                                at java.net.ServerSocket.implAccept(ServerSocket.java:216)
                                                                                at java.net.ServerSocket.accept(ServerSocket.java:140)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.waitForRequest(HttpProxyCacheServer.java:203)
                                                                                at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:55) 
                                                                                at com.danikula.videocache.HttpProxyCacheServer$WaitRequestsRunnable.run(HttpProxyCacheServer.java:317) 
                                                                                at java.lang.Thread.run(Thread.java:831) 
12-28 17:39:59.820 31345-31345/com.danikula.videocache.sample E/ProxyCache: Proxy server isn't pinged. Caching doesn't work. If you see this message, please, email me danikula@gmail.com
12-28 17:39:59.850 31345-31345/com.danikula.videocache.sample I/View: ssignParent(ViewParent parent) parent is: android.view.ViewRootImpl@3a70bc06
12-28 17:39:59.850 31345-31345/com.danikula.videocache.sample I/Choreographer: Skipped 641 frames!  The application may be doing too much work on its main thread.
12-28 17:39:59.950 31345-31345/com.danikula.videocache.sample I/AudioManager: requestAudioFocus() status : 1
12-28 17:39:59.950 31345-31345/com.danikula.videocache.sample I/AudioManager: requestAudioFocus() apk    : com.danikula.videocache.sample
12-28 17:39:59.960 31345-31345/com.danikula.videocache.sample I/MediaPlayer-JNI: throw_jni_exception_in_java;test for ART
12-28 17:39:59.960 31345-31345/com.danikula.videocache.sample I/MediaPlayer-JNI: throw_jni_exception_in_java;test for ART method
12-28 17:39:59.960 31345-31345/com.danikula.videocache.sample I/MediaPlayer-JNI: fields.throw_exception != NULL
12-28 17:39:59.960 31345-31345/com.danikula.videocache.sample I/MediaPlayer-JNI: throw_jni_exception_in_java;test for ART get method
12-28 17:39:59.960 31345-31345/com.danikula.videocache.sample I/MediaPlayer-JNI: throw_jni_exception_in_java;test for ART call java
12-28 17:39:59.960 31345-31345/com.danikula.videocache.sample E/MediaPlayer: throwsException:java/lang/IllegalStateException,callingMethod:android_media_MediaPlayer_getCurrentPosition
12-28 17:39:59.960 31345-31345/com.danikula.videocache.sample I/art_test: catch IllegalStateException
12-28 17:39:59.980 31345-31366/com.danikula.videocache.sample I/System: core_booster, getBoosterConfig = false
12-28 17:39:59.980 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]rx timeout:0
12-28 17:39:59.980 31345-31366/com.danikula.videocache.sample I/System.out: [socket][3] connection /172.17.10.81:1311;LocalPort=53456(0)
12-28 17:39:59.980 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]connect[/172.17.10.81:1311]
12-28 17:39:59.990 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]port[53456]
12-28 17:40:00.000 31345-31366/com.danikula.videocache.sample I/System.out: [socket][/192.168.253.57:53456] connected
12-28 17:40:02.190 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]rx timeout:100
12-28 17:40:02.300 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]rx timeout:0
12-28 17:40:02.300 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]close[53456]
12-28 17:40:02.300 31345-31366/com.danikula.videocache.sample I/System.out: close [socket][/0.0.0.0:53456]
12-28 17:40:02.300 31345-31366/com.danikula.videocache.sample I/System: core_booster, getBoosterConfig = false
12-28 17:40:02.300 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]rx timeout:0
12-28 17:40:02.310 31345-31366/com.danikula.videocache.sample I/System.out: [socket][4] connection /172.17.10.81:1311;LocalPort=33529(0)
12-28 17:40:02.310 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]connect[/172.17.10.81:1311]
12-28 17:40:02.330 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]port[33529]
12-28 17:40:02.330 31345-31366/com.danikula.videocache.sample I/System.out: [socket][/192.168.253.57:33529] connected
12-28 17:40:04.350 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]close[33529]
12-28 17:40:04.360 31345-31366/com.danikula.videocache.sample I/System.out: close [socket][/0.0.0.0:33529]
12-28 17:40:04.460 31345-31365/com.danikula.videocache.sample I/System: core_booster, getBoosterConfig = false
12-28 17:40:04.460 31345-31365/com.danikula.videocache.sample I/System.out: [CDS]rx timeout:0
12-28 17:40:04.460 31345-31365/com.danikula.videocache.sample I/System.out: [socket][5] connection /172.17.10.81:1311;LocalPort=45218(0)
12-28 17:40:04.460 31345-31365/com.danikula.videocache.sample I/System.out: [CDS]connect[/172.17.10.81:1311]
12-28 17:40:04.470 31345-31365/com.danikula.videocache.sample I/System.out: [CDS]port[45218]
12-28 17:40:04.480 31345-31365/com.danikula.videocache.sample I/System.out: [socket][/192.168.253.57:45218] connected
12-28 17:40:06.270 31345-31957/com.danikula.videocache.sample W/MediaPlayer: info/warning (3, 0)
12-28 17:40:12.370 31345-31359/com.danikula.videocache.sample W/art: Suspending all threads took: 5.436ms
12-28 17:40:32.440 31345-31366/com.danikula.videocache.sample I/System.out: [CDS]close[45218]
12-28 17:40:32.440 31345-31366/com.danikula.videocache.sample I/System.out: close [socket][/0.0.0.0:45218]
```
could you give any clue? thanks.

**Comment by linsea** [comment]
remind, the HttpURLConnection Implementation on Android L is:
com.android.okhttp.internal.http.HttpURLConnectionImpl:http://127.0.0.1:47013/ping

**Comment by shawwinbin** [comment]
I have same error

**Comment by danikula** [comment]
Duplicates [28](https://github.com/danikula/AndroidVideoCache/issues/28)
