### ISSUE TITLE
NullPointerException on Android 5.0

### ISSUE THREAD

**Issue by linsea** [danikula/AndroidVideoCache#48]
hi, I encounter this exception, it seems related to new io library okio:
log detail:
```

01-04 15:14:41.660: E/ProxyCache(17773): ProxyCache error
01-04 15:14:41.660: E/ProxyCache(17773): java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
01-04 15:14:41.660: E/ProxyCache(17773): 	at com.android.okio.OkBuffer.write(OkBuffer.java:574)
01-04 15:14:41.660: E/ProxyCache(17773): 	at com.android.okio.OkBuffer.read(OkBuffer.java:610)
01-04 15:14:41.660: E/ProxyCache(17773): 	at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:53)
01-04 15:14:41.660: E/ProxyCache(17773): 	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
01-04 15:14:41.660: E/ProxyCache(17773): 	at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
01-04 15:14:41.660: E/ProxyCache(17773): 	at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
01-04 15:14:41.660: E/ProxyCache(17773): 	at com.danikula.videocache.HttpUrlSource.read(HttpUrlSource.java:89)
01-04 15:14:41.660: E/ProxyCache(17773): 	at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:125)
01-04 15:14:41.660: E/ProxyCache(17773): 	at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
01-04 15:14:41.660: E/ProxyCache(17773): 	at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:178)
01-04 15:14:41.660: E/ProxyCache(17773): 	at java.lang.Thread.run(Thread.java:831)
01-04 15:14:41.710: E/ProxyCache(17773): Error fetching info from http://xa/b/c/2Daw450.mp4
01-04 15:14:41.710: E/ProxyCache(17773): java.io.FileNotFoundException: http://xa/b/c/2Daw450.mp4
01-04 15:14:41.710: E/ProxyCache(17773): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
01-04 15:14:41.710: E/ProxyCache(17773): 	at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:105)
01-04 15:14:41.710: E/ProxyCache(17773): 	at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:53)
01-04 15:14:41.710: E/ProxyCache(17773): 	at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:61)
01-04 15:14:41.710: E/ProxyCache(17773): 	at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:39)
01-04 15:14:41.710: E/ProxyCache(17773): 	at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
01-04 15:14:41.710: E/ProxyCache(17773): 	at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:221)
01-04 15:14:41.710: E/ProxyCache(17773): 	at com.danikula.videocache.HttpProxyCacheServer.access$300(HttpProxyCacheServer.java:55)
01-04 15:14:41.710: E/ProxyCache(17773): 	at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:331)
01-04 15:14:41.710: E/ProxyCache(17773): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-04 15:14:41.710: E/ProxyCache(17773): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-04 15:14:41.710: E/ProxyCache(17773): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-04 15:14:41.710: E/ProxyCache(17773): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-04 15:14:41.710: E/ProxyCache(17773): 	at java.lang.Thread.run(Thread.java:831)
```

**Comment by linsea** [comment]
duplicate issue, update to V2.3.4 would fix this.

**Comment by danikula** [comment]
@linsea It seems problem in your url `http://xa/b/c/2Daw450.mp4`
