### ISSUE TITLE
It's not working Nexus 5 android 6.0.1 

### ISSUE THREAD

**Issue by Himanshu4003** [danikula/AndroidVideoCache#53]
Here is my code : 

```` Java 
proxyCacheServer=BullTankApp.getProxy();

                    proxyUrl = proxyCacheServer.getProxyUrl((mUri.toString().replaceAll(" ","%20")));


                    proxyCacheServer.registerCacheListener(new CacheListener() {
                        @Override
                        public void onCacheAvailable(File cacheFile, String url, int percentsAvailable) {

                            LogUtil.w("LOG_TAG","Video Cache % is"+ percentsAvailable);

                        }
                    },mUri.getPath().replaceAll(" ", "%20"));


Here is our server example url of videos :

http://19823.45.67/webservices/uploads/3/covervideo/VID_20160125_153445-056a5f36238556.mp4
I can able to play this url without Proxy Cache in android.

```` Java
/com.yyyy E/ProxyCache: Error reading ping response
                                                          com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:50333/ping with offset 0
                                                              at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:66)
                                                              at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120)
                                                              at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55)
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339)
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                              at java.lang.Thread.run(Thread.java:818)
                                                           Caused by: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                              at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
                                                              at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
                                                              at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
                                                              at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
                                                              at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                              at com.splunk.mint.network.io.InputStreamMonitor.read(InputStreamMonitor.java:91)
                                                              at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
                                                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                              at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                                              at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
                                                              at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:138)
                                                              at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:61)
                                                              at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120) 
                                                              at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55) 
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339) 
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335) 
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                              at java.lang.Thread.run(Thread.java:818) 
                                                           Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                              at libcore.io.Posix.recvfromBytes(Native Method)
                                                              at libcore.io.Posix.recvfrom(Posix.java:189)
                                                              at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                              at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
                                                              at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481) 
                                                              at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java) 
                                                              at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237) 
                                                              at com.splunk.mint.network.io.InputStreamMonitor.read(InputStreamMonitor.java:91) 
                                                              at com.android.okhttp.okio.Okio$2.read(Okio.java:135) 
                                                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211) 
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
                                                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
                                                              at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191) 
                                                              at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80) 
                                                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904) 
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501) 
                                                              at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:138) 
                                                              at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:61) 
                                                              at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120) 
                                                              at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55) 
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339) 
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335) 
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                              at java.lang.Thread.run(Thread.java:818) 
01-28 15:36:51.510 12335-13305/com.yyyy E/ProxyCache: Error reading ping response
                                                          com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:50333/ping with offset 0
                                                              at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:66)
                                                              at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120)
                                                              at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55)
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339)
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                              at java.lang.Thread.run(Thread.java:818)
                                                           Caused by: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                              at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
                                                              at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
                                                              at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
                                                              at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
                                                              at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                              at com.splunk.mint.network.io.InputStreamMonitor.read(InputStreamMonitor.java:91)
                                                              at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
                                                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                              at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                                              at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
                                                              at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:138)
                                                              at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:61)
                                                              at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120) 
                                                              at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55) 
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339) 
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335) 
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                              at java.lang.Thread.run(Thread.java:818) 
                                                           Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                              at libcore.io.Posix.recvfromBytes(Native Method)
                                                              at libcore.io.Posix.recvfrom(Posix.java:189)
                                                              at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                              at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
                                                              at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481) 
                                                              at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java) 
                                                              at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237) 
                                                              at com.splunk.mint.network.io.InputStreamMonitor.read(InputStreamMonitor.java:91) 
                                                              at com.android.okhttp.okio.Okio$2.read(Okio.java:135) 
                                                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211) 
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
                                                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
                                                              at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191) 
                                                              at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80) 
                                                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904) 
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501) 
                                                              at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:138) 
                                                              at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:61) 
                                                              at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120) 
                                                              at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55) 
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339) 
                                                              at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335) 
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by shaopx** [comment]
i have also get error on Android 6.0 device.  here is the log
03-24 10:49:25.049 21442-22269/com.kingsoft D/ProxyCache: Open connection to http://127.0.0.1:48512/ping 
03-24 10:49:26.306 21442-22269/com.kingsoft E/ProxyCache: Error reading ping response 
com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:48512/ping with offset 0 
at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:66) 
at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120) 
at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55) 
at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339) 
at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
at java.lang.Thread.run(Thread.java:818) 
Caused by: java.io.FileNotFoundException: http://127.0.0.1:48512/ping 
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238) 
at com.xiaomi.mistatistic.sdk.a.a.getInputStream(Unknown Source) 
at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:63) 
at com.danikula.videocache.HttpProxyCacheServer.pingServer(HttpProxyCacheServer.java:120)  
at com.danikula.videocache.HttpProxyCacheServer.access$400(HttpProxyCacheServer.java:55)  
at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:339)  
at com.danikula.videocache.HttpProxyCacheServer$PingCallable.call(HttpProxyCacheServer.java:335)  
at java.util.concurrent.FutureTask.run(FutureTask.java:237)  
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)  
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)  
at java.lang.Thread.run(Thread.java:818)  
03-24 10:49:27.883 840-946/system_process D/ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 132] 
03-24 10:49:38.307 21442-21442/com.kingsoft E/ProxyCache: Shutdown server… Error pinging server [attempts: 3, max timeout: 12000]. If you see this message, please, email me danikula@gmail.com 
03-24 10:49:38.307 21442-21442/com.kingsoft I/ProxyCache: Shutdown proxy server 
03-24 10:49:38.308 21442-21442/com.kingsoft E/ProxyCache: Proxy server isn't pinged. Caching doesn't work. If you see this message, please, email me danikula@gmail.com

**Comment by shaopx** [comment]
try to use real local ip instead of 127.0.0.1
I have tested , it works fine in my phone

**Comment by danikula** [comment]
Duplicates [28](https://github.com/danikula/AndroidVideoCache/issues/28)
