### ISSUE TITLE
Too many error logs

### ISSUE THREAD

**Issue by ebomb** [danikula/AndroidVideoCache#54]
Hi,

Is it possible to add a function or flag to disable error logs? I am caching multiple videos and some videos are not available to download and that's fine, but our Logs are getting overflown with your proxy cache error logs. 

```
Example: (This is just for 1 video that throws an error)

E/ProxyCache: Error fetching info from MY_URL java.io.FileNotFoundException: MY_URL
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:210)
                                                                 at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:111)
                                                                 at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:53)
                                                                 at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:61)
                                                                 at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:39)
                                                                 at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:221)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.access$300(HttpProxyCacheServer.java:55)
                                                                 at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:331)
                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                 at java.lang.Thread.run(Thread.java:818)

E/ProxyCache: ProxyCache error
                                                             com.danikula.videocache.ProxyCacheException: Error opening connection for MY_URL with offset 0
                                                                 at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:66)
                                                                 at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:122)
                                                                 at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
                                                                 at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:179)
                                                                 at java.lang.Thread.run(Thread.java:818)
                                                              Caused by: java.io.FileNotFoundException: MY_URL
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:210)
                                                                 at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:63)
                                                                 at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:122) 
                                                                 at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19) 
                                                                 at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:179) 
                                                                 at java.lang.Thread.run(Thread.java:818) 

E/ProxyCache: HttpProxyCacheServer error
                                                             com.danikula.videocache.ProxyCacheException: Error processing request
                                                                 at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:228)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.access$300(HttpProxyCacheServer.java:55)
                                                                 at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:331)
                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                 at java.lang.Thread.run(Thread.java:818)
                                                              Caused by: com.danikula.videocache.ProxyCacheException: Error reading source 1 times
                                                                 at com.danikula.videocache.ProxyCache.checkReadSourceErrorsCount(ProxyCache.java:58)
                                                                 at com.danikula.videocache.ProxyCache.read(ProxyCache.java:44)
                                                                 at com.danikula.videocache.HttpProxyCache.responseWithCache(HttpProxyCache.java:78)
                                                                 at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:44)
                                                                 at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:221)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.access$300(HttpProxyCacheServer.java:55) 
                                                                 at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:331) 
                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                 at java.lang.Thread.run(Thread.java:818) 
```

**Comment by danikula** [comment]
Well I think it is important to log any problem. `AndroidVideoCache` uses `slf4j` for logging, so you can try to play with it. For example you can set you custom slf4j logger to mute any library's log output. 
From my side I won't do anything.
