### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mhemmings** [danikula/AndroidVideoCache#62]
Seeing this crash a lot:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.OkBuffer.write(OkBuffer.java:570)
       at com.android.okio.OkBuffer.read(OkBuffer.java:610)
       at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:56)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:465)
       at com.android.okhttp.internal.Util.skipAll(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:235)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:487)
       at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
       at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:580)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
       at com.danikula.videocache.HttpUrlSource.close(HttpUrlSource.java:80)
       at com.danikula.videocache.ProxyCache.closeSource(ProxyCache.java:160)
       at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:141)
       at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
       at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:179)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by geakw** [comment]
I also have this problem,how did you resolve it?

**Comment by swapnils-cuelogic** [comment]
I'm also facing this same issue. any workaround?

**Comment by danikula** [comment]
Related to [43](https://github.com/danikula/AndroidVideoCache/issues/43).
