### ISSUE TITLE
Crash byteCount < 0

### ISSUE THREAD

**Issue by prats226** [danikula/AndroidVideoCache#66]
```
Fatal Exception: java.lang.IllegalArgumentException: byteCount < 0: -1698
       at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:44)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
       at com.android.okhttp.internal.Util.skipAll(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:212)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:464)
       at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
       at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:439)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
       at com.danikula.videocache.HttpUrlSource.close(HttpUrlSource.java:80)
       at com.danikula.videocache.ProxyCache.closeSource(ProxyCache.java:160)`
```
Url is: https://v.cdn.vine.co/r/videos/934A8D50801329644842338467840_5f9739f91f1.9.0.16216443218969361547.mp4?versionId=4JsswMBvK51P.A_I9VWLaRpZRqxvmtoH

**Comment by rjain90** [comment]
I'm getting the same issue

**Comment by danikula** [comment]
Duplicates [66](https://github.com/danikula/AndroidVideoCache/issues/66)

**Comment by danikula** [comment]
Fixed here [here](https://github.com/danikula/AndroidVideoCache/commit/6c996ea66c857cf202c03835594ee6344b5fd3e0)
