### ISSUE TITLE
 com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException

### ISSUE THREAD

**Issue by SingleJie** [danikula/AndroidVideoCache#77]
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://127.0.0.1:51473/http%3A%2F%2Ffs1.rs.com%2Fgroup3%2FM00%2F0F%2FCB%2FCoSNWldxLVGAUoLMACrklWKXXAk524.m4a

**Comment by SingleJie** [comment]
on Buffreing pause player throw this exception

**Comment by danikula** [comment]
@SingleJie please provide full stacktrace.

**Comment by jessejohnson** [comment]
I've been experiencing the same error. @danikula here's my stacktrace

`10-23 10:16:57.378 9019-9772/? E/ExoPlayerImplInternal: Source error.
                                                        dependencies.amv$c: Unable to connect to http://127.0.0.1:38026/https%3A%2F%2Fcdn.asoriba.com%2Fmedia%2Fchurch%2Fmultimedia%2Fd80609188b444eb5aa91e28f6e9cfc2a.mp4
                                                            at dependencies.ams.a(:203)
                                                            at dependencies.amq.a(:123)
                                                            at dependencies.aka$a.c(:631)
                                                            at dependencies.amw$b.run(:295)
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                            at java.lang.Thread.run(Thread.java:764)
                                                         Caused by: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@af1e2534
                                                            at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
                                                            at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
                                                            at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
                                                            at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
                                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
                                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
                                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
                                                            at dependencies.ccz.h(Unknown Source:28)
                                                            at dependencies.ccx.getResponseCode(Unknown Source:2)
                                                            at dependencies.ams.a(:200)
                                                            at dependencies.amq.a(:123) 
                                                            at dependencies.aka$a.c(:631) 
                                                            at dependencies.amw$b.run(:295) 
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                            at java.lang.Thread.run(Thread.java:764) 
                                                         Caused by: java.io.EOFException: \n not found: size=0 content=...
                                                            at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
                                                            at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
                                                            at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) 
                                                            at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737) 
                                                            at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609) 
                                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471) 
                                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) 
                                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538) 
                                                            at dependencies.ccz.h(Unknown Source:28) 
                                                            at dependencies.ccx.getResponseCode(Unknown Source:2) 
                                                            at dependencies.ams.a(:200) 
                                                            at dependencies.amq.a(:123) 
                                                            at dependencies.aka$a.c(:631) 
                                                            at dependencies.amw$b.run(:295) 
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                            at java.lang.Thread.run(Thread.java:764) `

**Comment by firebaseempower** [comment]
facing Same issue is there is any solution available

**Comment by hojimani** [comment]
same here
using version 2.7.1

**Comment by zhufree** [comment]
same problem

**Comment by ron-diesel** [comment]
I need help too

**Comment by PrinceDholakiya** [comment]
Anyone have the solution to this.

**Comment by TonyAnine** [comment]
same problem

**Comment by vinnyA3** [comment]
same here

[**EDIT**]
Nevermind.  In my case, the video content needed to be sent over HTTPS.  Since android 9 (pie), all connections need to be over TLS unless you opt-in to clear text for specific domains.  I added some extra network security config as a workaround (at least until the third party sends all data via HTTPS).

**Comment by uzaysan** [comment]
This happens when app doesnt have read storage permission. I granted permission and it started to work again.
