### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Myeongwon-Kang** [danikula/AndroidVideoCache#79]
hi
Most occurred in 5.0.
i  use version 2.3.4

[log]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.OkBuffer.skip(OkBuffer.java:391)
       at com.android.okio.OkBuffer.clear(OkBuffer.java:386)
       at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:205)
       at com.android.okio.RealBufferedSource$1.close(RealBufferedSource.java:187)
       at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
       at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:583)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
       at com.danikula.videocache.HttpUrlSource.close(HttpUrlSource.java:80)
       at com.danikula.videocache.ProxyCache.closeSource(ProxyCache.java:160)
       at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:141)
       at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
       at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:179)
       at java.lang.Thread.run(Thread.java:818)

**Comment by danikula** [comment]
@Myeongwon-Kang it fixed in 2.5.0
