### ISSUE TITLE
ArrayIndexOutOfBoundsException while closing HttpUrlSource

### ISSUE THREAD

**Issue by Myeongwon-Kang** [danikula/AndroidVideoCache#88]
i used version 2.5.0
this is only from android 5.0
thanks

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.OkBuffer.write(OkBuffer.java:570)
       at com.android.okio.OkBuffer.read(OkBuffer.java:610)
       at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:56)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:465)
       at com.android.okhttp.internal.Util.skipAll(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:235)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:487)
       at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
       at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:580)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
       at com.danikula.videocache.HttpUrlSource.close(HttpUrlSource.java:80)
       at com.danikula.videocache.ProxyCache.closeSource(ProxyCache.java:160)
       at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:141)
       at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
       at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:179)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by danikula** [comment]
@Myeongwon-Kang Are you 100% sure this issue is reproduced on 2.5.0 version? This [problem](https://github.com/danikula/AndroidVideoCache/issues/43) was [fixed](https://github.com/danikula/AndroidVideoCache/commit/6c996ea66c857cf202c03835594ee6344b5fd3e0) in build 2.5.0.

**Comment by Myeongwon-Kang** [comment]
yes.
incurred only from 5.0!

**Comment by cagkanciloglu** [comment]
`Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.OkBuffer.skip(OkBuffer.java:391)
       at com.android.okio.OkBuffer.clear(OkBuffer.java:386)
       at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:205)
       at com.android.okio.RealBufferedSource$1.close(RealBufferedSource.java:187)
       at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
       at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:583)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
       at com.danikula.videocache.HttpUrlSource.close(SourceFile:86)
       at com.danikula.videocache.ProxyCache.closeSource(SourceFile:167)
       at com.danikula.videocache.ProxyCache.readSource(SourceFile:142)
       at com.danikula.videocache.ProxyCache.access$100(SourceFile:19)
       at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(SourceFile:186)
       at java.lang.Thread.run(Thread.java:818)`

I'm also having this issue. Only happens Android 5's. 
Version 2.6.0.

**Comment by phamd1989** [comment]
`com.android.okio.Util.checkOffsetAndCount (Util.java:29)
com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect (HttpURLConnectionImpl.java:113)
com.danikula.videocache.HttpUrlSource.close (HttpUrlSource.java:89)
com.danikula.videocache.ProxyCache.closeSource (ProxyCache.java:168)
com.danikula.videocache.ProxyCache.readSource (ProxyCache.java:143)
com.danikula.videocache.ProxyCache.access$100 (ProxyCache.java:19)
com.danikula.videocache.ProxyCache$SourceReaderRunnable.run (ProxyCache.java:187)
java.lang.Thread.run (Thread.java:818)`

still an issue on version 2.6.4
