### ISSUE TITLE
Error reading ping response: FileNotFoundException

### ISSUE THREAD

**Issue by zhangchf** [danikula/AndroidVideoCache#92]
```
10-12 14:09:48.321 26482-26765/com.mango.englishtalent E/Pinger: Error reading ping response
com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:42048/ping with offset 0
    at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
    at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
    at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.io.FileNotFoundException: http://127.0.0.1:42048/ping
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:242)
    at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
    at com.danikula.videocache.Pinger.pingServer(Pinger.java:86) 
    at com.danikula.videocache.Pinger.access$100(Pinger.java:28) 
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108) 
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 
10-12 14:09:48.371 26482-26765/com.mango.englishtalent E/Pinger: Error reading ping response
com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:42048/ping with offset 0
    at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
    at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
    at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.io.FileNotFoundException: http://127.0.0.1:42048/ping
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:242)
    at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
    at com.danikula.videocache.Pinger.pingServer(Pinger.java:86) 
    at com.danikula.videocache.Pinger.access$100(Pinger.java:28) 
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108) 
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 
10-12 14:09:48.441 26482-26765/com.mango.englishtalent E/Pinger: Error reading ping response
com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:42048/ping with offset 0
    at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
    at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
    at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.io.FileNotFoundException: http://127.0.0.1:42048/ping
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:242)
    at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
    at com.danikula.videocache.Pinger.pingServer(Pinger.java:86) 
    at com.danikula.videocache.Pinger.access$100(Pinger.java:28) 
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108) 
    at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 
10-12 14:09:48.441 26482-26482/com.mango.englishtalent E/Pinger: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
    at com.danikula.videocache.Pinger.ping(Pinger.java:67)
    at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:182)
    at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:81)
    at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:67)
    at com.mango.application.MangoApp.newProxy(MangoApp.java:518)
    at com.mango.application.MangoApp.getProxy(MangoApp.java:200)
    at com.mango.englishtalent.englishcorner.ClipMainActivity.initVideo(ClipMainActivity.java:105)
    at com.mango.englishtalent.englishcorner.ClipMainActivity.onCreate(ClipMainActivity.java:80)
    at android.app.Activity.performCreate(Activity.java:6876)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
    at android.app.ActivityThread.access$1100(ActivityThread.java:222)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7229)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by danikula** [comment]
Duplicates #134
