### ISSUE TITLE
Error closing socket output stream

### ISSUE THREAD

**Issue by zhangchf** [danikula/AndroidVideoCache#93]
```
10-12 14:15:34.731 26482-2536/com.mango.englishtalent E/HttpProxyCacheServer: HttpProxyCacheServer error
com.danikula.videocache.ProxyCacheException: Error closing socket output stream
at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:294)
at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270)
at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242)
at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
at java.net.PlainSocketImpl.shutdownOutput(PlainSocketImpl.java:373)
at java.net.Socket.shutdownOutput(Socket.java:654)
at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:291)
at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242) 
at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
at java.lang.Thread.run(Thread.java:818) 
Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
at libcore.io.Posix.shutdown(Native Method)
at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:159)
at java.net.PlainSocketImpl.shutdownOutput(PlainSocketImpl.java:371)
at java.net.Socket.shutdownOutput(Socket.java:654) 
at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:291) 
at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242) 
at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
at java.lang.Thread.run(Thread.java:818) 
```

**Comment by jabalsick** [comment]
Hi! I would like to know if exists some workaround for this issue?

**Comment by AssIstne** [comment]
I got this error too.
when I want to load a mp4 from a url, I got a `com.danikula.videocache.ProxyCacheException` every time after clearing the cache.

It can be produced in sample project.
change the code below in `SingleVideoActivity`
```
@Override
protected void onCreate(Bundle state) {
    super.onCreate(state);
    // url of map
    String url = "https://video.wbiao.cn/4671521875_9158257275_3137319443.mp4";
    if (state == null) {
        getSupportFragmentManager()
                .beginTransaction()
                .add(R.id.containerView, VideoFragment.build(url, getExternalCacheDir().getPath()))// change the build method
                .commit();
    }
}
```

I test this in Samsung S5, API 21 and Samsung GT-I9100, API 15.
And sometime it throws `com.danikula.videocache.ProxyCacheException`,  but the video plays.

```
11-03 19:04:05.039 17378-17945/com.danikula.videocache.sample E/HttpProxyCacheServer: HttpProxyCacheServer error
        com.danikula.videocache.ProxyCacheException: Error closing socket output stream
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:294)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
        Caused by: java.net.SocketException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.shutdownOutput(PlainSocketImpl.java:377)
        at java.net.Socket.shutdownOutput(Socket.java:652)
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:291)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
        Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Posix.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:149)
        at java.net.PlainSocketImpl.shutdownOutput(PlainSocketImpl.java:375)
        at java.net.Socket.shutdownOutput(Socket.java:652) 
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:291) 
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
```

Thanks for any help in advanced

**Comment by AssIstne** [comment]
And I noticed that after clear cache, it will print a message which is a weird uri.
```
com.danikula.videocache.sample D/VideoFragment: Use proxy url http://127.0.0.1:51940/https%3A%2F%2Fvideo.wbiao.cn%2F4671521875_9158257275_3137319443.mp4 instead of original url https://video.wbiao.cn/4671521875_9158257275_3137319443.mp4
```

**Comment by bravekingzhang** [comment]
```java
private void closeSocketOutput(Socket socket) {
        try {
            **if (socket.isConnected()** && !socket.isOutputShutdown()) {
                socket.shutdownOutput();
            }
        } catch (IOException e) {
            onError(new ProxyCacheException("Error closing socket output stream", e));
        }
    }
```

**Comment by danikula** [comment]
It is normal situation. Server (proxy) doesn't know that client has already closed connection (user closed activity and released VideoView) so can't close output stream normally. 

@bravekingzhang your solution doesn't work. In this case `socket.isConnected()` will return `true`.

In build 2.6.4 I don't log this error, just log warning.

**Comment by mohitbhansali** [comment]
@danikula still facing this error. Any solution for this?

**Comment by codewith-pk** [comment]
@danikula Still Facing this issue. Is there any solution of this ?
My Android studio Log is after playing every video

```
E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error closing socket input stream
```

**Comment by musaabshirgar1** [comment]
@praveenverma720 same. Any Solution?
