### ISSUE TITLE
Error pinging server (attempts: 3, max timeout: 280).

### ISSUE THREAD

**Issue by MarkMjw** [danikula/AndroidVideoCache#94]
call HttpProxyCacheServer.shutdown() when exit app (not kill the process), then launch app from launcher. and the log:

E/Pinger: Error reading ping response
                                                            com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:38119/ping with offset 0
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:73)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:85)
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:27)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:107)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:103)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 38119): connect failed: ECONNREFUSED (Connection refused)
                                                                at libcore.io.IoBridge.connect(IoBridge.java:124)
                                                                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                at java.net.Socket.connect(Socket.java:882)
                                                                at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
                                                                at com.android.okhttp.Connection.connect(Connection.java:1194)
                                                                at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
                                                                at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:295)
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
                                                                at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:157)
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:66)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:85) 
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:27) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:107) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:103) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                at java.lang.Thread.run(Thread.java:818) 
                                                             Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
                                                                at libcore.io.Posix.connect(Native Method)
                                                                at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
                                                                at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
                                                                at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456) 
                                                                at java.net.Socket.connect(Socket.java:882) 
                                                                at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139) 
                                                                at com.android.okhttp.Connection.connect(Connection.java:1194) 
                                                                at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392) 
                                                                at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:295) 
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373) 
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323) 
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491) 
                                                                at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:157) 
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:66) 
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:85) 
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:27) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:107) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:103) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                at java.lang.Thread.run(Thread.java:818) 
E/Pinger: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                             com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                                 at com.danikula.videocache.Pinger.ping(Pinger.java:66)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:180)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:117)
                                                                 at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:98)

**Comment by danikula** [comment]
Duplicates #134
