### ISSUE TITLE
Error pinging server (attempts: 3, max timeout: 280). If you see this message, please

### ISSUE THREAD

**Issue by EzenwakaKaycee** [danikula/AndroidVideoCache#96]
10-22 03:55:02.942 25963-25963/com.kolobi.android W/Pinger: Error pinging server (attempt: 0, timeout: 70). 
10-22 03:55:03.084 25963-25963/com.kolobi.android W/Pinger: Error pinging server (attempt: 1, timeout: 140). 
10-22 03:55:03.365 25963-25963/com.kolobi.android W/Pinger: Error pinging server (attempt: 2, timeout: 280). 
10-22 03:55:03.430 25963-25963/com.kolobi.android E/Pinger: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                            com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                                at com.danikula.videocache.Pinger.ping(Pinger.java:67)
                                                                at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:182)
                                                                at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:81)
                                                                at com.danikula.videocache.HttpProxyCacheServer.<init>(HttpProxyCacheServer.java:52)
                                                                at com.danikula.videocache.HttpProxyCacheServer$Builder.build(HttpProxyCacheServer.java:424)
                                                                at com.kolobi.android.MyApplication.newProxy(MyApplication.java:46)
                                                                at com.kolobi.android.MyApplication.getProxy(MyApplication.java:39)
                                                                at com.kolobi.android.ui.view.KolobiVideo.playVideo(KolobiVideo.java:69)
                                                                at com.kolobi.android.ui.view.CellFeedViewHolder$1.onClick(CellFeedViewHolder.java:130)
                                                                at android.view.View.performClick(View.java:4757)
                                                                at android.view.View$PerformClick.run(View.java:19757)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5233)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
10-22 03:55:03.430 25963-25963/com.kolobi.android I/HttpProxyCacheServer: Proxy cache server started. Is it alive? false
10-22 03:55:03.509 25963-25963/com.kolobi.android W/Pinger: Error pinging server (attempt: 0, timeout: 70). 
10-22 03:55:03.650 25963-25963/com.kolobi.android W/Pinger: Error pinging server (attempt: 1, timeout: 140). 
10-22 03:55:03.684 25963-26685/com.kolobi.android E/Pinger: Error reading ping response
                                                            com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:35881/ping with offset 0
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: java.io.FileNotFoundException: http://127.0.0.1:35881/ping
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86) 
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                at java.lang.Thread.run(Thread.java:818) 
10-22 03:55:03.867 25963-26685/com.kolobi.android E/Pinger: Error reading ping response
                                                            com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:35881/ping with offset 0
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: java.io.FileNotFoundException: http://127.0.0.1:35881/ping
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86) 
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                at java.lang.Thread.run(Thread.java:818) 
10-22 03:55:03.931 25963-25963/com.kolobi.android W/Pinger: Error pinging server (attempt: 2, timeout: 280). 
10-22 03:55:03.939 25963-25963/com.kolobi.android E/Pinger: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                            com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, email me danikula@gmail.com or create issue here https://github.com/danikula/AndroidVideoCache/issues
                                                                at com.danikula.videocache.Pinger.ping(Pinger.java:67)
                                                                at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:182)
                                                                at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:119)
                                                                at com.kolobi.android.ui.view.KolobiVideo.playVideo(KolobiVideo.java:71)
                                                                at com.kolobi.android.ui.view.CellFeedViewHolder$1.onClick(CellFeedViewHolder.java:130)
                                                                at android.view.View.performClick(View.java:4757)
                                                                at android.view.View$PerformClick.run(View.java:19757)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5233)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
10-22 03:55:03.942 25963-25963/com.kolobi.android I/Choreographer: Skipped 123 frames!  The application may be doing too much work on its main thread.
10-22 03:55:04.009 25963-26057/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null
10-22 03:55:04.039 25963-26057/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null
10-22 03:55:04.062 25963-26685/com.kolobi.android E/Pinger: Error reading ping response
                                                            com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:35881/ping with offset 0
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: java.io.FileNotFoundException: http://127.0.0.1:35881/ping
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86) 
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                at java.lang.Thread.run(Thread.java:818) 
10-22 03:55:04.373 25963-26685/com.kolobi.android E/Pinger: Error reading ping response
                                                            com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:35881/ping with offset 0
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: java.io.FileNotFoundException: http://127.0.0.1:35881/ping
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86) 
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                at java.lang.Thread.run(Thread.java:818) 
10-22 03:55:04.615 25963-26685/com.kolobi.android E/Pinger: Error reading ping response
                                                            com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:35881/ping with offset 0
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: java.io.FileNotFoundException: http://127.0.0.1:35881/ping
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86) 
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                at java.lang.Thread.run(Thread.java:818) 
10-22 03:55:04.803 25963-26685/com.kolobi.android E/Pinger: Error reading ping response
                                                            com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:35881/ping with offset 0
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: java.io.FileNotFoundException: http://127.0.0.1:35881/ping
                                                                at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
                                                                at com.danikula.videocache.Pinger.pingServer(Pinger.java:86) 
                                                                at com.danikula.videocache.Pinger.access$100(Pinger.java:28) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108) 
                                                                at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                at java.lang.Thread.run(Thread.java:818)

**Comment by taany6210** [comment]
我找到问题了，我这边的是因为开了代理会出现这个错误，去除代理就好了。

**Comment by danikula** [comment]
Duplicates [92](https://github.com/danikula/AndroidVideoCache/issues/92)

**Comment by poojashelke** [comment]
this helps me..

<application 
    android:networkSecurityConfig="@xml/network_security_config"
    ...>

and

res/xml/network_security_config.xml

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>

**Comment by poojashelke** [comment]
<application 
    android:networkSecurityConfig="@xml/network_security_config"
    ...>


res/xml/network_security_config.xml

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
