### ISSUE TITLE
Accepting Self-Signed HTTPS Certificates

### ISSUE THREAD

**Issue by userdevd** [danikula/AndroidVideoCache#98]
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
                                                                       at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
                                                                       at com.android.okhttp.Connection.connect(Connection.java:143)
                                                                       at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                                       at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                                       at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
                                                                       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)

**Comment by danikula** [comment]
@userdevd Where is `AndroidVideoCache` in your stacktrace?
